In [2]:
import pandas as pd
import numpy as np

In [3]:
train_df = pd.read_csv('/Users/hesu/Documents/KT/riiid/train.csv')

In [4]:
train_df.head(10)

row_id  timestamp  user_id  content_id  content_type_id  task_container_id  \
0       0          0      115        5692                0                  1   
1       1      56943      115        5716                0                  2   
2       2     118363      115         128                0                  0   
3       3     131167      115        7860                0                  3   
4       4     137965      115        7922                0                  4   
5       5     157063      115         156                0                  5   
6       6     176092      115          51                0                  6   
7       7     194190      115          50                0                  7   
8       8     212463      115        7896                0                  8   
9       9     230983      115        7863                0                  9   

   user_answer  answered_correctly  prior_question_elapsed_time  \
0            3                   1                          NaN   
1            2                   1                      37000.0   
2            0                   1                      55000.0   
3            0                   1                      19000.0   
4            1                   1                      11000.0   
5            2                   1                       5000.0   
6            0                   1                      17000.0   
7            3                   1                      17000.0   
8            2                   1                      16000.0   
9            0                   1                      16000.0   

  prior_question_had_explanation  
0                            NaN  
1                          False  
2                          False  
3                          False  
4                          False  
5                          False  
6                          False  
7                          False  
8                          False  
9                          False

In [5]:
test_df = train_df.head(100)

In [15]:
test_df

row_id  timestamp  user_id  content_id  content_type_id  \
0        0          0      115        5692                0   
1        1      56943      115        5716                0   
2        2     118363      115         128                0   
3        3     131167      115        7860                0   
4        4     137965      115        7922                0   
..     ...        ...      ...         ...              ...   
95      95     835457     2746         484                0   
96      96          0     5382        5000                0   
97      97      39828     5382        3944                0   
98      98     132189     5382         217                0   
99      99     153727     5382        5844                0   

    task_container_id  user_answer  answered_correctly  \
0                   1            3                   1   
1                   2            2                   1   
2                   0            0                   1   
3                   3            0                   1   
4                   4            1                   1   
..                ...          ...                 ...   
95                 19            0                   1   
96                  0            0                   1   
97                  1            1                   0   
98                  2            0                   1   
99                  3            1                   0   

    prior_question_elapsed_time prior_question_had_explanation  new_qid  
0                           NaN                            NaN     5692  
1                       37000.0                          False     5716  
2                       55000.0                          False      128  
3                       19000.0                          False     7860  
4                       11000.0                          False     7922  
..                          ...                            ...      ...  
95                      20000.0                           True      484  
96                          NaN                            NaN     5000  
97                      24000.0                          False    17467  
98                      35000.0                          False      217  
99                      88000.0                          False    19367  

[100 rows x 11 columns]

In [16]:
test_df.loc[test_df['answered_correctly']==0, 'content_id'] = test_df['content_id'] + 13523

/anaconda3/envs/torch1.4/lib/python3.7/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


In [17]:
test_df

row_id  timestamp  user_id  content_id  content_type_id  \
0        0          0      115        5692                0   
1        1      56943      115        5716                0   
2        2     118363      115         128                0   
3        3     131167      115        7860                0   
4        4     137965      115        7922                0   
..     ...        ...      ...         ...              ...   
95      95     835457     2746         484                0   
96      96          0     5382        5000                0   
97      97      39828     5382       17467                0   
98      98     132189     5382         217                0   
99      99     153727     5382       19367                0   

    task_container_id  user_answer  answered_correctly  \
0                   1            3                   1   
1                   2            2                   1   
2                   0            0                   1   
3                   3            0                   1   
4                   4            1                   1   
..                ...          ...                 ...   
95                 19            0                   1   
96                  0            0                   1   
97                  1            1                   0   
98                  2            0                   1   
99                  3            1                   0   

    prior_question_elapsed_time prior_question_had_explanation  new_qid  
0                           NaN                            NaN     5692  
1                       37000.0                          False     5716  
2                       55000.0                          False      128  
3                       19000.0                          False     7860  
4                       11000.0                          False     7922  
..                          ...                            ...      ...  
95                      20000.0                           True      484  
96                          NaN                            NaN     5000  
97                      24000.0                          False    17467  
98                      35000.0                          False      217  
99                      88000.0                          False    19367  

[100 rows x 11 columns]

In [7]:
def get_qid(qid, ans):
    if ans == 1:
        return qid
    else:
        return qid + 13523

In [10]:
test_df.columns

Index(['row_id', 'timestamp', 'user_id', 'content_id', 'content_type_id',
       'task_container_id', 'user_answer', 'answered_correctly',
       'prior_question_elapsed_time', 'prior_question_had_explanation'],
      dtype='object')

In [12]:
test_df['new_qid'] = test_df.apply(lambda x: get_qid(x.content_id, x.answered_correctly), axis=1)

/anaconda3/envs/torch1.4/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [13]:
test_df

row_id  timestamp  user_id  content_id  content_type_id  \
0        0          0      115        5692                0   
1        1      56943      115        5716                0   
2        2     118363      115         128                0   
3        3     131167      115        7860                0   
4        4     137965      115        7922                0   
..     ...        ...      ...         ...              ...   
95      95     835457     2746         484                0   
96      96          0     5382        5000                0   
97      97      39828     5382        3944                0   
98      98     132189     5382         217                0   
99      99     153727     5382        5844                0   

    task_container_id  user_answer  answered_correctly  \
0                   1            3                   1   
1                   2            2                   1   
2                   0            0                   1   
3                   3            0                   1   
4                   4            1                   1   
..                ...          ...                 ...   
95                 19            0                   1   
96                  0            0                   1   
97                  1            1                   0   
98                  2            0                   1   
99                  3            1                   0   

    prior_question_elapsed_time prior_question_had_explanation  new_qid  
0                           NaN                            NaN     5692  
1                       37000.0                          False     5716  
2                       55000.0                          False      128  
3                       19000.0                          False     7860  
4                       11000.0                          False     7922  
..                          ...                            ...      ...  
95                      20000.0                           True      484  
96                          NaN                            NaN     5000  
97                      24000.0                          False    17467  
98                      35000.0                          False      217  
99                      88000.0                          False    19367  

[100 rows x 11 columns]

In [14]:
class Rii_dataset_train(Dataset):
    def __init__(self,df ):
        self.df = df
    def __len__(self):
        return len(self.df)
    def __getitem__(self, index):


SyntaxError: unexpected EOF while parsing (<ipython-input-14-5dd2a2b22bcf>, line 6)

In [18]:
import torch

In [19]:
a = torch.randn([2,4,6])

In [20]:
a.shape

torch.Size([2, 4, 6])

In [21]:
a.dim()

3

In [22]:
a = torch.randn(48,1)
b = torch.randn(48, 50264)

In [23]:
a.dim()

2

In [24]:
b.dim()

2

In [25]:
a = torch.randint(50264,(48,1))

In [26]:
a

tensor([[ 9460],
        [33971],
        [19977],
        [38437],
        [36321],
        [47649],
        [27892],
        [ 6467],
        [ 5620],
        [18891],
        [ 6523],
        [39622],
        [39383],
        [42366],
        [25763],
        [19363],
        [25903],
        [43773],
        [38717],
        [17224],
        [42966],
        [49133],
        [19322],
        [39505],
        [33618],
        [18271],
        [35313],
        [13477],
        [  610],
        [14867],
        [35068],
        [24321],
        [44824],
        [34093],
        [ 2187],
        [ 9185],
        [37946],
        [49003],
        [ 2582],
        [15831],
        [45086],
        [15563],
        [  639],
        [ 9565],
        [20334],
        [16557],
        [29046],
        [32947]])

In [27]:
a.shape

torch.Size([48, 1])

In [28]:
target = torch.randint(50264, (48,1))

In [29]:
lprobs = torch.rand([48,50264])

In [30]:
lprobs.shape

torch.Size([48, 50264])

In [31]:
lprobs

tensor([[0.0127, 0.4663, 0.5933,  ..., 0.4461, 0.6927, 0.7143],
        [0.6527, 0.0757, 0.7406,  ..., 0.7533, 0.0894, 0.1856],
        [0.5865, 0.1540, 0.5221,  ..., 0.3686, 0.8813, 0.8366],
        ...,
        [0.4942, 0.9205, 0.2240,  ..., 0.7193, 0.8629, 0.4389],
        [0.2202, 0.9485, 0.9802,  ..., 0.0835, 0.1157, 0.2907],
        [0.3521, 0.9785, 0.3581,  ..., 0.9012, 0.3303, 0.3006]])

In [32]:
nll_loss = lprobs.gather(dim=-1, index=target)

In [33]:
nll_loss

tensor([[0.2601],
        [0.1393],
        [0.8423],
        [0.8845],
        [0.7558],
        [0.7334],
        [0.3009],
        [0.1727],
        [0.2303],
        [0.5292],
        [0.8180],
        [0.1596],
        [0.9755],
        [0.6182],
        [0.5205],
        [0.2599],
        [0.1628],
        [0.4998],
        [0.8561],
        [0.9199],
        [0.3897],
        [0.3733],
        [0.5948],
        [0.8170],
        [0.2105],
        [0.5066],
        [0.2212],
        [0.6646],
        [0.3409],
        [0.6873],
        [0.3400],
        [0.8953],
        [0.0752],
        [0.2194],
        [0.9777],
        [0.7289],
        [0.0071],
        [0.9153],
        [0.2209],
        [0.0525],
        [0.4050],
        [0.2847],
        [0.1110],
        [0.5877],
        [0.6400],
        [0.4380],
        [0.9183],
        [0.1358]])

In [34]:
nll_loss.shape

torch.Size([48, 1])

In [35]:
lprobs

tensor([[0.0127, 0.4663, 0.5933,  ..., 0.4461, 0.6927, 0.7143],
        [0.6527, 0.0757, 0.7406,  ..., 0.7533, 0.0894, 0.1856],
        [0.5865, 0.1540, 0.5221,  ..., 0.3686, 0.8813, 0.8366],
        ...,
        [0.4942, 0.9205, 0.2240,  ..., 0.7193, 0.8629, 0.4389],
        [0.2202, 0.9485, 0.9802,  ..., 0.0835, 0.1157, 0.2907],
        [0.3521, 0.9785, 0.3581,  ..., 0.9012, 0.3303, 0.3006]])

In [37]:
lprobs[0][40141]

tensor(0.2601)

In [36]:
target

tensor([[40141],
        [30400],
        [20171],
        [ 6766],
        [17560],
        [27963],
        [22304],
        [ 3376],
        [36573],
        [12049],
        [32356],
        [17995],
        [44983],
        [36669],
        [ 8441],
        [21711],
        [11671],
        [35674],
        [26128],
        [37249],
        [30130],
        [44052],
        [42702],
        [36845],
        [ 5338],
        [24073],
        [41857],
        [34329],
        [29322],
        [17812],
        [40213],
        [31753],
        [37606],
        [17477],
        [24506],
        [ 1649],
        [49382],
        [32912],
        [ 7455],
        [ 3301],
        [17950],
        [41766],
        [24892],
        [15552],
        [39079],
        [30028],
        [33040],
        [ 8153]])

In [38]:
pad_mask= target.eq(8153)

In [39]:
pad_mask

tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True]])

In [40]:
nll_loss

tensor([[0.2601],
        [0.1393],
        [0.8423],
        [0.8845],
        [0.7558],
        [0.7334],
        [0.3009],
        [0.1727],
        [0.2303],
        [0.5292],
        [0.8180],
        [0.1596],
        [0.9755],
        [0.6182],
        [0.5205],
        [0.2599],
        [0.1628],
        [0.4998],
        [0.8561],
        [0.9199],
        [0.3897],
        [0.3733],
        [0.5948],
        [0.8170],
        [0.2105],
        [0.5066],
        [0.2212],
        [0.6646],
        [0.3409],
        [0.6873],
        [0.3400],
        [0.8953],
        [0.0752],
        [0.2194],
        [0.9777],
        [0.7289],
        [0.0071],
        [0.9153],
        [0.2209],
        [0.0525],
        [0.4050],
        [0.2847],
        [0.1110],
        [0.5877],
        [0.6400],
        [0.4380],
        [0.9183],
        [0.1358]])

In [41]:
nll_loss.masked_fill_(pad_mask,0.0)

tensor([[0.2601],
        [0.1393],
        [0.8423],
        [0.8845],
        [0.7558],
        [0.7334],
        [0.3009],
        [0.1727],
        [0.2303],
        [0.5292],
        [0.8180],
        [0.1596],
        [0.9755],
        [0.6182],
        [0.5205],
        [0.2599],
        [0.1628],
        [0.4998],
        [0.8561],
        [0.9199],
        [0.3897],
        [0.3733],
        [0.5948],
        [0.8170],
        [0.2105],
        [0.5066],
        [0.2212],
        [0.6646],
        [0.3409],
        [0.6873],
        [0.3400],
        [0.8953],
        [0.0752],
        [0.2194],
        [0.9777],
        [0.7289],
        [0.0071],
        [0.9153],
        [0.2209],
        [0.0525],
        [0.4050],
        [0.2847],
        [0.1110],
        [0.5877],
        [0.6400],
        [0.4380],
        [0.9183],
        [0.0000]])

In [42]:
w = torch.empty(3,5)

In [43]:
w

tensor([[0.0000e+00, 0.0000e+00, 7.1037e+09, 2.0005e+00, 1.1210e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [44]:
w = torch.empty(1)

In [45]:
w

tensor([0.])

In [47]:
torch.nn.init.uniform_(w)

tensor([0.1916])

In [48]:
emb = torch.randn([2,3,46])

In [49]:
emb

tensor([[[ 1.1996e+00, -1.5580e+00,  2.0268e-01,  5.2686e-02,  7.6731e-01,
           6.0023e-01,  8.1248e-02,  7.5454e-01,  3.9815e-01,  2.0955e-01,
           1.7664e-01, -1.2472e-01,  1.0662e+00, -6.8378e-01,  2.4561e-01,
           1.5582e+00, -8.3121e-01,  1.3526e+00, -1.3202e+00,  1.1542e+00,
          -8.7792e-01,  6.4724e-01, -4.4402e-01,  2.5612e-01,  6.8766e-01,
          -2.8318e+00,  9.2781e-01, -3.4088e-01,  4.4471e-02,  1.0628e+00,
           5.5053e-01,  1.0512e-01,  1.2656e+00, -5.0288e-01,  5.0880e-01,
           3.8443e-01,  5.6463e-01,  5.2456e-01, -2.6841e-01, -3.9559e-01,
           7.7989e-01,  3.8371e-01,  1.7162e-01, -5.5135e-01,  8.6088e-01,
           1.0989e+00],
         [-4.1473e-01, -1.6013e+00, -2.1530e-02,  2.2680e+00,  8.5087e-01,
           1.3420e+00,  8.8448e-01, -1.1135e+00, -1.2012e-01,  3.2434e-01,
          -1.2372e+00,  5.8207e-01,  1.1579e+00, -3.6937e-01,  8.0025e-01,
          -1.9785e+00,  7.5390e-01,  1.1327e+00,  1.2340e+00,  1.2962e+00,
 

In [50]:
c = emb * w

In [51]:
c

tensor([[[ 2.2984e-01, -2.9850e-01,  3.8832e-02,  1.0094e-02,  1.4701e-01,
           1.1500e-01,  1.5567e-02,  1.4457e-01,  7.6285e-02,  4.0149e-02,
           3.3843e-02, -2.3896e-02,  2.0428e-01, -1.3101e-01,  4.7058e-02,
           2.9854e-01, -1.5926e-01,  2.5915e-01, -2.5295e-01,  2.2113e-01,
          -1.6821e-01,  1.2401e-01, -8.5073e-02,  4.9072e-02,  1.3175e-01,
          -5.4256e-01,  1.7776e-01, -6.5310e-02,  8.5204e-03,  2.0363e-01,
           1.0548e-01,  2.0141e-02,  2.4248e-01, -9.6350e-02,  9.7484e-02,
           7.3655e-02,  1.0818e-01,  1.0050e-01, -5.1426e-02, -7.5794e-02,
           1.4942e-01,  7.3517e-02,  3.2881e-02, -1.0564e-01,  1.6494e-01,
           2.1055e-01],
         [-7.9461e-02, -3.0681e-01, -4.1250e-03,  4.3453e-01,  1.6302e-01,
           2.5713e-01,  1.6946e-01, -2.1334e-01, -2.3014e-02,  6.2142e-02,
          -2.3704e-01,  1.1152e-01,  2.2184e-01, -7.0771e-02,  1.5332e-01,
          -3.7907e-01,  1.4444e-01,  2.1702e-01,  2.3642e-01,  2.4835e-01,
 

AttributeError: module 'torch' has no attribute 'uniform'

In [53]:
import torch

In [54]:
a = torch.uniform(1)

AttributeError: module 'torch' has no attribute 'uniform'

In [55]:
a = torch.randn(1)

In [56]:
a

tensor([-0.2613])

In [58]:
torch.nn.init.uniform_(a)

tensor([0.5064])

In [59]:
a

tensor([0.5064])

In [60]:
b = torch.nn.init.uniform_(a)

In [61]:
b

tensor([0.1381])

In [62]:
b

tensor([0.1381])

In [64]:
c = torch.LongTensor(b.long())

In [65]:
c

tensor([0])

In [66]:
from difflib import SequenceMatcher

In [67]:
src = [3276,531,5,882,8,6,2156]
trg = [3276,531,8,5,882,6,302]

In [68]:
matcher = SequenceMatcher(None, src, trg)

In [69]:
diffs = list(matcher.get_opcodes())

In [70]:
for diff in diffs:
    print(diff)

('equal', 0, 2, 0, 2)
('insert', 2, 2, 2, 3)
('equal', 2, 4, 3, 5)
('delete', 4, 5, 5, 5)
('equal', 5, 6, 5, 6)
('replace', 6, 7, 6, 7)


In [72]:
import torch

In [73]:
a = torch.tensor([3276,531,5,882,8,6,2156])

In [74]:
a

tensor([3276,  531,    5,  882,    8,    6, 2156])

In [75]:
b = torch.tensor([3276,531,8,5,882,6,302])

In [76]:
matcher2 = SequenceMatcher(None, a, b)

In [77]:
diffs2 = list(matcher2.get_opcodes())

In [78]:
for diff in diffs2:
    print(diff)

('equal', 0, 2, 0, 2)
('replace', 2, 7, 2, 7)


In [79]:
a

tensor([3276,  531,    5,  882,    8,    6, 2156])

In [80]:
b

tensor([3276,  531,    8,    5,  882,    6,  302])

In [81]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [86]:
c = a.tolist()

In [87]:
c

[[1, 2, 3], [4, 5, 6]]

In [89]:
a = torch.tensor([[2,2,2,0,0,0],[2,2,0,0,0,0]])

In [90]:
tgt_lengths = torch.LongTensor([e.ne(0).long().sum() for e in a] )

In [91]:
tgt_lengths

tensor([3, 2])

In [92]:
srcs = torch.tensor([[3276,531,5,882,8,6,2156],[3276,531,5,882,8,6,2156]])
trgs = torch.tensor([[3276,531,8,5,882,6,302],[3276,531,8,5,882,6,302]])

In [93]:
srcs_list = srcs.tolist()

In [94]:
trgs_list = trgs.tolist()

In [95]:
srcs_list

[[3276, 531, 5, 882, 8, 6, 2156], [3276, 531, 5, 882, 8, 6, 2156]]

In [96]:
trgs_list

[[3276, 531, 8, 5, 882, 6, 302], [3276, 531, 8, 5, 882, 6, 302]]

In [97]:
res = []

In [99]:
for i in range(len(srcs_list)):
    src = srcs_list[i]
    trg = trgs_list[i]
    
    matcher = SequenceMatcher(None, src, trg)
    diffs = list(matcher.get_opcodes())
    
    ans = [1 for _ in range(len(trg))]
    for diff in diffs:
        print(diff)
        tag,i1,i2,j1,j2 = diff
        if tag != 'equal':
            ans[j1:j2] = [2 for _ in range(j2-j1)]
    res.append(ans)
    print("\n\n")

('equal', 0, 2, 0, 2)
('insert', 2, 2, 2, 3)
('equal', 2, 4, 3, 5)
('delete', 4, 5, 5, 5)
('equal', 5, 6, 5, 6)
('replace', 6, 7, 6, 7)



('equal', 0, 2, 0, 2)
('insert', 2, 2, 2, 3)
('equal', 2, 4, 3, 5)
('delete', 4, 5, 5, 5)
('equal', 5, 6, 5, 6)
('replace', 6, 7, 6, 7)





In [100]:
res

[[1, 1, 2, 1, 1, 1, 2], [1, 1, 2, 1, 1, 1, 2]]

In [101]:
res_tensor = torch.LongTensor(res)

In [102]:
res_tensor

tensor([[1, 1, 2, 1, 1, 1, 2],
        [1, 1, 2, 1, 1, 1, 2]])

In [110]:
c = [torch.tensor([2,3,4,5,6]), torch.tensor([4,5,6,7,8])]

In [111]:
size = max(v.size(0) for v in c)

In [112]:
res = c[0].new(len(c), size).fill_(1)

In [113]:
res

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [114]:
res[1][2:4] = 4

In [115]:
res

tensor([[1, 1, 1, 1, 1],
        [1, 1, 4, 4, 1]])

In [116]:
nll_loss = torch.randn(48,1)

In [117]:
nll_loss.shape

torch.Size([48, 1])

In [118]:
nll_loss = torch.tensor([1,2,3])

In [119]:
weight = torch.tensor([1,1,2])

In [120]:
res = nll_loss * weight

In [121]:
res

tensor([1, 2, 6])

In [127]:
a = torch.randint(1,10,(2,3))

In [128]:
a

tensor([[9, 8, 2],
        [1, 6, 7]])

In [130]:
mask = torch.tensor([1,0])

In [132]:
a = a.permute(1,0)

In [133]:
a

tensor([[9, 1],
        [8, 6],
        [2, 7]])

In [134]:
c = a*mask

In [135]:
c

tensor([[9, 0],
        [8, 0],
        [2, 0]])

In [136]:
c = c.permute(1,0)

In [137]:
c

tensor([[9, 8, 2],
        [0, 0, 0]])

In [138]:
679
680             label = item[3].to(device).float()
681
682 #             print("In evaluation x shape is:{}\t taret_id shape is:{}\t label shape is:{}".format(x.shape, ta    rget_id.shape,label.shape))
683
684             output = model(enc_que, enc_part, dec_ans)
685 #             print("Output shape is:{}\tlabel shape is:{}".format(output.shape, label.shape))
686
687             output_loss = output[:, -1:]
688             loss = criterion(output_loss, label)
689             eval_loss.append(loss.item())
690
691             output = output[:,-1]
692             label = label[:, -1]
693             pred = (torch.sigmoid(output) >= 0.5).long()
694
695             num_corrects += (pred == label).sum().item()
696             num_total += len(label)

SyntaxError: invalid syntax (<ipython-input-138-3f0b25fec70b>, line 2)

In [ ]:
class SAKTDataset(Dataset):
    def __init__(self, group, n_skill,n_ela_skill, max_seq=MAX_SEQ): #HDKIM 100
        super(SAKTDataset, self).__init__()
        self.max_seq = max_seq
        self.n_skill = n_skill
        self.n_ela_skill = n_ela_skill
        self.samples = group
        
#         self.user_ids = [x for x in group.index]
        self.enc_que = []
        self.enc_part = []
        self.dec_ans = []
        self.label = []

        self.user_ids = []
        for user_id in group.index:
            q_, qa_,ela_,part_,com_ = group[user_id]
            if len(q_) < 2: #HDKIM 10
                continue
            self.user_ids.append(user_id)
            
            #HDKIM Memory reduction
#             if len(q)>self.max_seq:
#                 group[user_id] = (q[-self.max_seq:],qa[-self.max_seq:], ela[-self.max_seq:])
            length = min(self.max_seq, len(q_))
            for i in range(2,length):
                
                q = np.ones(self.max_seq, dtype=int)*13523
                qa = np.zeros(self.max_seq, dtype=int)
                ela = np.ones(self.max_seq, dtype=int)*301
                part = np.ones(self.max_seq, dtype=int)*7
                com = np.ones(self.max_seq, dtype=int)*4

                q[-i:] = q_[:i].copy()
                qa[-i:] = qa_[:i].copy()
                ela[-i:] = ela_[:i].copy()                
                part[-i:] = part_[:i].copy()                
                com[-i:] = com_[:i].copy()                
  
                self.enc_que.append(q)
                self.enc_part.append(qa)
                self.dec_ans.append()
    
    def __len__(self):
        return len(self.user_ids)

        
    
    def __getitem__(self, index):
        user_id = self.user_ids[index]
        q_, qa_,ela_,part_,com_ = self.samples[user_id]
        seq_len = len(q_)

        q = np.ones(self.max_seq, dtype=int)*13523
        qa = np.zeros(self.max_seq, dtype=int)
        ela = np.ones(self.max_seq, dtype=int)*301
        part = np.ones(self.max_seq, dtype=int)*7
        com = np.ones(self.max_seq, dtype=int)*4

        if seq_len >= self.max_seq:
            if random.random() >0.1:
                start = random.randint(0, (seq_len-self.max_seq))
                end = start + self.max_seq
                q[:] = q_[start:end]
                qa[:] = qa_[start:end]
                ela[:] = ela_[start:end]
                part[:] = part_[start:end]
                com[:] = com_[start:end]

            else:   
                q[:] = q_[-self.max_seq:]
                qa[:] = qa_[-self.max_seq:]
                ela[:] = ela_[-self.max_seq:]
                part[:] = part_[-self.max_seq:]
                com[:] = com_[-self.max_seq:]
                
                
        else:
            if random.random() > 0.1:
                start = 0
                end = random.randint(2, seq_len)
                seq_len = end -start
                q[-seq_len:] = q_[0:seq_len]
                qa[-seq_len:] = qa_[0:seq_len]
                ela[-seq_len:] = ela_[0:seq_len]
                part[-seq_len:] = part_[0:seq_len]
                com[-seq_len:] = com_[0:seq_len]
                
            else:
                q[-seq_len:] = q_
                qa[-seq_len:] = qa_
                ela[-seq_len:] = ela_   
                part[-seq_len:] = part_   
                com[-seq_len:] = com_   
            
        label = qa[:]
        
        # encoder输入，从0开始一直到len 
        enc_que = np.ones(self.max_seq, dtype=int)*13523
        enc_que = q[:].copy()
        
        enc_part = np.ones(self.max_seq, dtype=int)*7
        enc_part = part[:].copy()
        
        enc_com = np.ones(self.max_seq, dtype=int)*4
        enc_com = com[:].copy()
        
        # decoder输入， 先在左边pad一个位置，然后从0一直到len-1
        dec_ela = np.ones(self.max_seq, dtype=int)*301
        dec_ela[1:] = ela[:-1].copy()
        
        dec_ans = np.zeros(self.max_seq, dtype=int)
        dec_ans[1:] = qa[:-1].copy()
        

        
        return enc_que, enc_part, enc_com, dec_ans,  label
        
        
#         return x, target_id,ela_x,ela_target,part_x,part_target,com_x,com_target,ans_x,label
    # x和target_id都是来自于q，存在一个错位，x比target_id提前一个位置
    # 所以我们可以尝试将ela 也分为ela_x和ela_target_id

In [ ]:
class SAKTDataset(Dataset):
247     def __init__(self, group, n_skill,n_ela_skill, max_seq=MAX_SEQ): #HDKIM 100
248         super(SAKTDataset, self).__init__()
249         self.max_seq = max_seq
250         self.n_skill = n_skill
251         self.n_ela_skill = n_ela_skill
252         self.samples = group
253
254 #         self.user_ids = [x for x in group.index]
255         self.user_ids = []
256         for user_id in group.index:
257             q, qa,ela = group[user_id]
258             if len(q) < 5: #HDKIM 10
259                 continue
260             self.user_ids.append(user_id)
261
262             #HDKIM Memory reduction
263             if len(q)>self.max_seq:
264                 group[user_id] = (q[-self.max_seq:],qa[-self.max_seq:], ela[-self.max_seq:])
265
266     def __len__(self):
267         return len(self.user_ids)
268
269     def __getitem__(self, index):
270         user_id = self.user_ids[index]
271         q_, qa_,ela_ = self.samples[user_id]
272         seq_len = len(q_)

274         q = np.zeros(self.max_seq, dtype=int)
275         qa = np.zeros(self.max_seq, dtype=int)
276         ela = np.zeros(self.max_seq, dtype=int)
277
278         if seq_len >= self.max_seq:
279             q[:] = q_[-self.max_seq:]
280             qa[:] = qa_[-self.max_seq:]
281             ela[:] = ela_[-self.max_seq:]
282         else:
283             q[-seq_len:] = q_
284             qa[-seq_len:] = qa_
285             ela[-seq_len:] = ela_
286
287         target_id = q[1:]
288         label = qa[1:]
289         ela_target = ela[1:]
290
291         x = np.zeros(self.max_seq-1, dtype=int)
292         x = q[:-1].copy()
293         x += (qa[:-1] == 1) * self.n_skill
294
295         ela_x = np.zeros(self.max_seq-1, dtype=int)
296         ela_x = ela[:-1].copy()
297         ela_x += (qa[:-1]==1) * self.n_ela_skill
298
299         return x, target_id,ela_x,ela_target,label

In [141]:
a = torch.randint(0,10,(2,4,10))

In [142]:
a

tensor([[[7, 3, 0, 6, 2, 5, 7, 4, 6, 8],
         [4, 9, 9, 7, 2, 5, 1, 9, 0, 3],
         [4, 0, 7, 7, 7, 2, 5, 8, 3, 4],
         [5, 7, 1, 4, 8, 8, 7, 8, 8, 5]],

        [[3, 4, 5, 0, 0, 5, 4, 9, 0, 9],
         [2, 3, 6, 4, 5, 2, 4, 4, 5, 3],
         [2, 6, 3, 8, 9, 0, 4, 2, 0, 6],
         [4, 5, 7, 2, 5, 0, 0, 5, 8, 3]]])

In [163]:
adj = torch.randint(0,2,(4,4))

In [164]:
adj

tensor([[1, 1, 0, 0],
        [0, 0, 1, 1],
        [1, 1, 0, 1],
        [1, 1, 1, 1]])

In [158]:
w = torch.randn(10,10)

In [159]:
w = w.long()

In [161]:
w_a = torch.matmul(a, w)

In [162]:
w_a

tensor([[[  9,  14,  18,  -1,  -7,  12,   2,   5,   4,  13],
         [  8,  25,  30, -13,   1,  32,  -2,  -6, -11,  15],
         [  9,   9,  11,   3,  -3,  -3,  -1,   4,  -5,   5],
         [ 12,  17,  38,  -8,  -8,  11,  -4,  -2,   4,  12]],

        [[ 14,  18,  18,  -5,  -6,  25,  -9,   5,  19,  27],
         [ 10,  10,  15,  -1,  -6,  -1,   0,   0,   0,  -3],
         [ 25,  28,  21,  -2,  -4,  -2,   6,   0,  -2,  -2],
         [ 12,   3,  15,  -5,  -7,   1,  -3,  -2,  -2,  -7]]])

In [165]:
res = torch.matmul(adj, w_a)

In [166]:
res

tensor([[[ 17,  39,  48, -14,  -6,  44,   0,  -1,  -7,  28],
         [ 21,  26,  49,  -5, -11,   8,  -5,   2,  -1,  17],
         [ 29,  56,  86, -22, -14,  55,  -4,  -3,  -3,  40],
         [ 38,  65,  97, -19, -17,  52,  -5,   1,  -8,  45]],

        [[ 24,  28,  33,  -6, -12,  24,  -9,   5,  19,  24],
         [ 37,  31,  36,  -7, -11,  -1,   3,  -2,  -4,  -9],
         [ 36,  31,  48, -11, -19,  25, -12,   3,  17,  17],
         [ 61,  59,  69, -13, -23,  23,  -6,   3,  15,  15]]])

In [167]:
eye = torch.eye(4)

In [168]:
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [169]:
a = torch.randn(2,3
               \
                
                
                
                            

SyntaxError: unexpected EOF while parsing (<ipython-input-169-6f30bfe17eed>, line 6)

In [174]:
a = torch.randn(2,3,1)

In [175]:
c = a.squeeze(-1)

In [176]:
c

tensor([[ 0.4876,  0.7969,  1.1045],
        [ 0.9932, -0.0494, -0.1053]])

In [177]:
c.shape

torch.Size([2, 3])

In [178]:
train_df = pd.read_csv('/Users/hesu/Documents/KT/riiid/user_seq/train_200_valid_2_more_data.csv')

In [179]:
train_df.columns

Index(['user_id', 'values'], dtype='object')

In [181]:
train_df.head(10)

user_id                                             values
0      115  (array([5692, 5716,  128, 7860, 7922,  156,   ...
1      124  (array([7900, 7876,  175, 1278, 2063, 2065, 20...
2     2746  (array([ 5273,   758,  5976,   236,   404,   3...
3     5382  (array([ 5000,  3944,   217,  5844,  5965,  49...
4     8623  (array([ 3915,  4750,  6456,  3968,  6104,  57...
5     8701  (array([ 3901,  6671,  4963,  6143,  8279,  39...
6    12741  (array([ 8750,  5952,  9133,  6016, 11183,  44...
7    13134  (array([12137, 12119, 12124, 12215, 11916, 121...
8    24418  (array([ 3951,  8469,  6081,  9796,  6299,  41...
9    24600  (array([ 7900,  7876,   175,  1278,  2064,  20...

In [183]:
user_id = train_df.iloc[0,0]

In [184]:
user_id

115

In [185]:
print(type(user_id))

<class 'numpy.int64'>


In [186]:
values = train_df.iloc[0,1]

In [187]:
values

'(array([5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,\n        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,\n         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,\n       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363],\n      dtype=int16), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,\n       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0],\n      dtype=int8), array([24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,\n       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,\n       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,\n       21., 17., 17., 17., 14.]), array([4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3]))'

In [188]:
print(type(values))

<class 'str'>


In [189]:
v = np.fromstring(values)

/anaconda3/envs/torch1.4/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


ValueError: string size must be a multiple of element size

In [190]:
values

'(array([5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,\n        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,\n         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,\n       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363],\n      dtype=int16), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,\n       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0],\n      dtype=int8), array([24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,\n       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,\n       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,\n       21., 17., 17., 17., 14.]), array([4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3]))'

In [199]:
splits = values.replace("(","").replace(")","").replace("\n","").replace(" dtype=int16,","").replace("dtype=int8,","").replace("[","").replace("]","")

In [200]:
splits

'array5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363,      array1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,       array24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,       21., 17., 17., 17., 14., array4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3'

In [201]:
arrays = splits.split('array')

In [202]:
arrays

['',
 '5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363,      ',
 '1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,       ',
 '24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,       21., 17., 17., 17., 14., ',
 '4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3']

In [205]:
arrs = arrays[1:]

In [206]:
arrs

['5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363,      ',
 '1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,       ',
 '24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,       21., 17., 17., 17., 14., ',
 '4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3']

In [215]:
num1 = arrs[1]
nums = num1.strip().split(',')

In [216]:
nums

['1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 0',
 ' 0',
 ' 0',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 0',
 ' 1',
 ' 1',
 ' 0',
 ' 0',
 '       0',
 ' 0',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 0',
 ' 1',
 ' 0',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 0',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 0',
 ' 1',
 ' 0',
 '']

In [217]:
nums = [int(e.strip()) for e in nums[:-1]]

In [218]:
nums

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0]

In [219]:
len(nums)

44

In [220]:
len(train_df)

3223939

In [223]:
train_df['user_id']

0                 115
1                 124
2                2746
3                5382
4                8623
              ...    
3223934   -2147482273
3223935   -2147482892
3223936   -2147482889
3223937   -2147482903
3223938   -2147482901
Name: user_id, Length: 3223939, dtype: int64

In [ ]:
dict_country = data.set_index('project').T.to_dict('list')


In [224]:
d = train_df.set_index('user_id').T.to_list('list')

KeyboardInterrupt: 

In [225]:
df = train_df.head(100)

In [227]:
d = df.set_index('user_id').T

In [229]:
def get_v(values):
    a = []
    splits = values.replace("(","").replace(")","").replace("\n","").replace(" dtype=int16,","").replace("dtype=int8,","").replace("[","").replace("]","")
    
    arrays = splits.split('array')
    
    for i in range(1, len(arrays)):
        num1 = arrays[i]
        nums = num1.strip().split(',')  
        nums = [int(e.strip()) for e in nums[:-1]]
        a.append(nums)
        print(len(nums))
    print("####")

In [228]:
d

user_id                                             115     \
values   (array([5692, 5716,  128, 7860, 7922,  156,   ...   

user_id                                             124     \
values   (array([7900, 7876,  175, 1278, 2063, 2065, 20...   

user_id                                             2746    \
values   (array([ 5273,   758,  5976,   236,   404,   3...   

user_id                                             5382    \
values   (array([ 5000,  3944,   217,  5844,  5965,  49...   

user_id                                             8623    \
values   (array([ 3915,  4750,  6456,  3968,  6104,  57...   

user_id                                             8701    \
values   (array([ 3901,  6671,  4963,  6143,  8279,  39...   

user_id                                             12741   \
values   (array([ 8750,  5952,  9133,  6016, 11183,  44...   

user_id                                             13134   \
values   (array([12137, 12119, 12124, 12215, 11916, 121...   

user_id                                             24418   \
values   (array([ 3951,  8469,  6081,  9796,  6299,  41...   

user_id                                             24600   ...  \
values   (array([ 7900,  7876,   175,  1278,  2064,  20...  ...   

user_id                                             469162  \
values   (array([ 7900,  7876,   175,  1278,  2065,  20...   

user_id                                             475020  \
values   (array([ 2017,  2015,  1136, 10149, 10150, 101...   

user_id                                             478631  \
values   (array([ 3961,  4239,  8284,  4458,  5324,  92...   

user_id                                             480368  \
values   (array([ 3819,   910,  5511,   218,   296,  42...   

user_id                                             496840  \
values   (array([  126, 10517,    69,  7934,   129, 104...   

user_id                                             508795  \
values   (array([ 5960,  4830,  5465,  5269,  5592,  58...   

user_id                                             510560  \
values   (array([ 4753,  3923,  5509,  6309,  3684,  51...   

user_id                                             513434  \
values   (array([ 5576,  6099,  6208,  4665,   379,  40...   

user_id                                             531584  \
values   (array([ 5464,  4265,  3988,  3986,  3654,  47...   

user_id                                             537732  
values   (array([6278, 5761, 9261, 5123, 5844, 5177, 38...  

[1 rows x 100 columns]

In [237]:
for k in d.keys():
    v = d[k]
#     v = str(v)
    t = np.array(v)
    print(type(v))
    print(t[0])
#     v = get_v(v)

<class 'pandas.core.series.Series'>
(array([5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,
        104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,
         45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,
       7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2063, 2064, 3363],
      dtype=int16), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0],
      dtype=int8), array([24., 37., 55., 19., 11.,  5., 17., 17., 16., 16., 17., 22., 23.,
       21., 24., 22., 21., 20., 18., 17., 29., 20., 19., 21., 22., 16.,
       20., 22., 22., 23., 20., 15., 20., 20., 22., 19., 17., 20., 17.,
       21., 17., 17., 17., 14.]), array([4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3]))
<class 'pandas.core.series.Series'>
(array([7900, 7876,  175, 1278, 2063, 2065, 2064, 

In [ ]:
group = train_df[['user_id','values']].groupby('user_id').apply(lambda r:(r['values'].values))

In [ ]:
def get_values(values):
    values = values.replace("(","").replace(")","").replace("\n","").replace(" dtype=int16,","").replace("dtype=int8,","").replace("[","").replace("]","")
    splits = values.split('array')
    
    res = []
    for i in range(1, len(splits)-1):
        nums = splits[i]
        num = nums.strip().split(',')  
        num = [int(e.strip().replace(".","")) for e in num[:-1]]
        res.append(num)
#         print(len(num))
    nums = splits[-1]
    num = nums.strip().split(',')  
    num = [int(e.strip().replace(".","")) for e in num]
    res.append(num)
#     print(len(num))
    return np.array(res)

In [238]:
df = pd.read_csv('/Users/hesu/Documents/KT/riiid/user_seq/train_200_valid_2_4values.csv')

In [239]:
df.head(10)

user_id                                             value1  \
0      115  [5692 5716  128 7860 7922  156   51   50 7896 ...   
1      124  [7900 7876  175 1278 2063 2065 2064 3364 3363 ...   
2     2746  [ 5273   758  5976   236   404   382   405   8...   
3     5382  [ 5000  3944   217  5844  5965  4990  5235  60...   
4     8623  [ 3915  4750  6456  3968  6104  5738  6435  54...   
5     8701  [ 3901  6671  4963  6143  8279  3964  4002   7...   
6    12741  [ 8750  5952  9133  6016 11183  4424 11280  99...   
7    13134  [12137 12119 12124 12215 11916 12194 12054 119...   
8    24418  [ 3951  8469  6081  9796  6299  4174  4612  47...   
9    24600  [ 7900  7876   175  1278  2064  2065  2063  33...   

                                              value2  \
0  [1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0...   
1  [1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1...   
2                [0 0 0 1 0 1 1 1 1 0 1 1 0 1 0 1 1]   
3  [1 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0...   
4  [1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1...   
5                    [1 1 1 0 1 0 0 0 1 0 0 1 1 1 0]   
6  [1 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1...   
7  [1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1...   
8  [1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1...   
9  [1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0...   

                                              value3  \
0  [24 37 55 19 11  5 17 17 16 16 17 22 23 21 24 ...   
1  [24 26 29 26 18 18 18 33 33 33 21 21 21 21 21 ...   
2  [24 28 17 24 20 16 16 19 18 18 20 13 13 16 15 ...   
3  [ 24  24  35  88  18  12   5  92  70  14  79  ...   
4  [24 16 33 30 40 35 30 29 15 19 14 38 21 17 16 ...   
5     [24 13 15 24 25 44 17 39 16 18 18 18 18 22 16]   
6  [ 43  45  22  23  19  36  33  49  29  29  29  ...   
7  [20 18 17 20 15 18 13 13 18 18 18 33 23 21 18 ...   
8  [13 15 44 24 30 22 18  5  4 20  7  7  7  7 35 ...   
9  [24 24 23 22 18 18 18 24 24 24 22 22 22 15 15 ...   

                                              value4  
0  [4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  
1  [0 0 0 1 2 2 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 5...  
2                [4 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1]  
3  [4 4 1 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0...  
4  [4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 4 4 4 4 4 4 4...  
5                    [4 4 4 4 4 4 4 1 1 1 1 1 1 1 1]  
6  [4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5...  
7  [1 1 1 1 1 1 1 1 3 3 3 0 0 0 0 0 0 0 0 0 0 0 1...  
8  [4 4 4 4 4 4 4 4 4 4 5 5 5 5 4 4 4 4 4 4 4 4 4...  
9  [0 0 0 1 2 2 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 5...

In [274]:
one = df.iloc[0,4]

In [275]:
one

'[4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 1 2 2 2 3]'

In [276]:
type(one)

str

In [277]:
def from_np_array(array_string):
    array_string = ','.join(array_string.replace('[ ', '[').split())
    return np.array(ast.literal_eval(array_string))

In [278]:
def get_values(values):
    values = values.replace("(","").replace(")","").replace("\n","").replace(" dtype=int16,","").replace("dtype=int8,","").replace("[","").replace("]","")
    splits = values.split('array')
    
    res = []
    for i in range(1, len(splits)-1):
        nums = splits[i]
        num = nums.strip().split(',')  
        num = [int(e.strip().replace(".","")) for e in num[:-1]]
        res.append(num)
#         print(len(num))
    nums = splits[-1]
    num = nums.strip().split(',')  
    num = [int(e.strip().replace(".","")) for e in num]
    res.append(num)
#     print(len(num))
    return np.array(res)

In [ ]:
def get_values(value):
    value = value.replace("[","").replace("]","").replace("\n","")
    nums = one.strip().split()
    nums = [int(e) for e in nums]
    
    return nums

In [279]:
one = one.replace("[","").replace("]","").replace("\n","")

In [280]:
one

'4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 2 3'

In [281]:
nums = one.strip().split()

In [282]:
nums = [int(e) for e in nums]

In [283]:
len(nums)

44

In [284]:
nums

[4,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 2,
 3]

In [309]:
import gc

In [310]:
def get_values(value):
    value = value.replace("[","").replace("]","").replace("\n","")
    nums = value.strip().split()
#     nums = [int(e) for e in nums]
#     gc.collect()
    nums = np.array(nums)
    nums = nums.astype(np.int16)
#     gc.collect()
    return nums

In [311]:
df = pd.read_csv('/Users/hesu/Documents/KT/riiid/user_seq/train_200_valid_2_4values.csv',
                converters={'value1':get_values,'value2':get_values,'value3':get_values,'value4':get_values,})

In [292]:
df.head(10)

user_id                                             value1  \
0      115  [5692, 5716, 128, 7860, 7922, 156, 51, 50, 789...   
1      124  [7900, 7876, 175, 1278, 2063, 2065, 2064, 3364...   
2     2746  [5273, 758, 5976, 236, 404, 382, 405, 873, 531...   
3     5382  [5000, 3944, 217, 5844, 5965, 4990, 5235, 6050...   
4     8623  [3915, 4750, 6456, 3968, 6104, 5738, 6435, 549...   
5     8701  [3901, 6671, 4963, 6143, 8279, 3964, 4002, 754...   
6    12741  [8750, 5952, 9133, 6016, 11183, 4424, 11280, 9...   
7    13134  [12137, 12119, 12124, 12215, 11916, 12194, 120...   
8    24418  [3951, 8469, 6081, 9796, 6299, 4174, 4612, 473...   
9    24600  [7900, 7876, 175, 1278, 2064, 2065, 2063, 3363...   

                                              value2  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, ...   
1  [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...   
2  [0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, ...   
3  [1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, ...   
4  [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...   
5      [1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0]   
6  [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...   
7  [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, ...   
8  [1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, ...   
9  [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              value3  \
0  [24, 37, 55, 19, 11, 5, 17, 17, 16, 16, 17, 22...   
1  [24, 26, 29, 26, 18, 18, 18, 33, 33, 33, 21, 2...   
2  [24, 28, 17, 24, 20, 16, 16, 19, 18, 18, 20, 1...   
3  [24, 24, 35, 88, 18, 12, 5, 92, 70, 14, 79, 66...   
4  [24, 16, 33, 30, 40, 35, 30, 29, 15, 19, 14, 3...   
5  [24, 13, 15, 24, 25, 44, 17, 39, 16, 18, 18, 1...   
6  [43, 45, 22, 23, 19, 36, 33, 49, 29, 29, 29, 2...   
7  [20, 18, 17, 20, 15, 18, 13, 13, 18, 18, 18, 3...   
8  [13, 15, 44, 24, 30, 22, 18, 5, 4, 20, 7, 7, 7...   
9  [24, 24, 23, 22, 18, 18, 18, 24, 24, 24, 22, 2...   

                                              value4  
0  [4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, ...  
2  [4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
3  [4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, ...  
4  [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, ...  
5      [4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1]  
6  [4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, ...  
7  [1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 0, 0, 0, 0, ...  
8  [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 4, ...  
9  [0, 0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, ...

In [299]:
one = df.iloc[0,4]

In [300]:
one

array([4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3],
      dtype=int16)

In [301]:
import cudf

ModuleNotFoundError: No module named 'cudf'

In [302]:
!pip install cudf

  ERROR: Command errored out with exit status 1:
   command: /anaconda3/envs/torch1.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vn/9lmrj0994cngv302ddhb6j0h0000gn/T/pip-install-to9206ma/cudf/setup.py'"'"'; __file__='"'"'/private/var/folders/vn/9lmrj0994cngv302ddhb6j0h0000gn/T/pip-install-to9206ma/cudf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/vn/9lmrj0994cngv302ddhb6j0h0000gn/T/pip-wheel-1gw2v11a
       cwd: /private/var/folders/vn/9lmrj0994cngv302ddhb6j0h0000gn/T/pip-install-to9206ma/cudf/
  Complete output (25 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/vn/9lmrj0994cngv302ddhb6j0h0000gn/T

In [313]:
import torch

In [316]:
logits = torch.randn(2,2,2)

In [317]:
logits

tensor([[[-0.2381,  0.4857],
         [-0.4578,  0.0118]],

        [[ 0.6282,  0.0636],
         [-1.0967, -0.0796]]])

In [319]:
targets.shape

torch.Size([2, 2, 2])

In [320]:
targets = torch.tensor([[1,1],[0,1]])

In [321]:
targets.shape

torch.Size([2, 2])

In [323]:
logits_flat = logits.view(-1, logits.size(-1))

In [324]:
logits_flat.shape

torch.Size([4, 2])

In [325]:
log_probs_flat = torch.nn.functional.log_softmax(logits_flat, dim=-1)


In [326]:
log_probs_flat

tensor([[-1.1192, -0.3954],
        [-0.9553, -0.4856],
        [-0.4502, -1.0148],
        [-1.3258, -0.3087]])

In [327]:
log_probs_flat.shape

torch.Size([4, 2])

In [328]:
targets_flat = targets.view(-1, 1).long()


In [329]:
targets_flat.shape

torch.Size([4, 1])

In [330]:
negative_log_likelihood_flat = - torch.gather(log_probs_flat, dim=1, index=targets_flat)


In [331]:
negative_log_likelihood_flat

tensor([[0.3954],
        [0.4856],
        [0.4502],
        [0.3087]])

In [332]:
negative_log_likelihood_flat.shape

torch.Size([4, 1])

In [333]:
negative_log_likelihood = negative_log_likelihood_flat.view(*targets.size())


In [334]:
negative_log_likelihood

tensor([[0.3954, 0.4856],
        [0.4502, 0.3087]])

In [335]:
negative_log_likelihood.shape

torch.Size([2, 2])

In [340]:
weights = torch.tensor([[1,1],[1,0]])

In [341]:
negative_log_likelihood = negative_log_likelihood * weights.float()


In [342]:
negative_log_likelihood

tensor([[0.3954, 0.4856],
        [0.4502, 0.0000]])

In [344]:
per_batch_loss = negative_log_likelihood.sum(1) / (weights.sum(1).float() + 1e-13)
per_batch_loss

tensor([0.4405, 0.4502])

In [345]:
num_non_empty_sequences = ((weights.sum(1) > 0).float().sum() + 1e-13)
num_non_empty_sequences

tensor(2.)

In [347]:
loss = per_batch_loss.sum() / num_non_empty_sequences
loss

tensor(0.4453)

In [349]:
output = torch.randn(16,100)

In [350]:
output = output[:,-1]

In [351]:
output.shape

torch.Size([16])

In [352]:
output

tensor([ 0.3317, -0.2669,  0.4234, -0.6401, -0.6972,  1.3790, -0.4424, -0.2122,
        -0.5731,  0.6453,  1.2340,  0.0071, -1.9100,  0.2001, -0.6717,  0.3526])

In [353]:
pred = (torch.sigmoid(output) >=0.5).long()

In [354]:
pred

tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1])

In [357]:
label = torch.randint(0,2,(16,))

In [358]:
label

tensor([1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [359]:
num_corrects = (pred == label).sum().item()

In [360]:
num_corrects

9

In [366]:
import torch.nn.functional as F


# train

In [361]:
output

tensor([ 0.3317, -0.2669,  0.4234, -0.6401, -0.6972,  1.3790, -0.4424, -0.2122,
        -0.5731,  0.6453,  1.2340,  0.0071, -1.9100,  0.2001, -0.6717,  0.3526])

In [362]:
output.shape

torch.Size([16])

In [425]:
output = torch.randn(16,100,2)

In [426]:
output.shape

torch.Size([16, 100, 2])

In [427]:
output = output[:,-1,:]

In [428]:
class_probs = F.softmax(output, dim=-1)

In [429]:
class_probs.shape

torch.Size([16, 2])

In [467]:
max_vals = torch.max(class_probs, dim=-1)

In [468]:
idx = max_vals[1]

In [469]:
idx

tensor([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1])

In [431]:
idx = max_vals[1].tolist()
idx = torch.LongTensor(idx)

In [432]:
idx

tensor([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1])

In [433]:
idx.shape

torch.Size([16])

In [434]:
pred = idx

In [435]:
label = torch.randint(0,2,(16,100))

In [436]:
label = label[:,-1]

In [437]:
label

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1])

In [480]:
type(label)

torch.Tensor

In [438]:
num_corrects = (pred == label).sum().item()

In [439]:
num_corrects

11

In [440]:
output

tensor([[ 1.5550,  1.7018],
        [ 0.2340, -1.9665],
        [ 1.9392,  1.7009],
        [ 0.2210, -0.2310],
        [ 0.3684, -0.2880],
        [ 0.5676,  1.1496],
        [-0.4225, -0.1491],
        [ 0.1394, -0.0851],
        [-1.6651, -0.2104],
        [-0.0787,  1.4250],
        [ 0.3141, -0.0566],
        [-3.4404, -0.1952],
        [ 0.1833, -1.6470],
        [-3.1230, -1.6080],
        [ 2.0295, -0.4522],
        [ 0.2354,  1.6667]])

In [441]:
output.shape

torch.Size([16, 2])

In [442]:
output = output[:,1:]

In [444]:
output = output.view(-1)

In [445]:
output

tensor([ 1.7018, -1.9665,  1.7009, -0.2310, -0.2880,  1.1496, -0.1491, -0.0851,
        -0.2104,  1.4250, -0.0566, -0.1952, -1.6470, -1.6080, -0.4522,  1.6667])

In [446]:
outs = []
labels = []

In [447]:
labels.extend(label.view(-1).data.cpu().numpy())
outs.extend(output.view(-1).data.cpu().numpy())

In [448]:
from sklearn.metrics import roc_auc_score


In [450]:
auc = roc_auc_score(labels, outs)
auc

0.8

# test

In [385]:
output = torch.randn(16,100)

In [386]:
output = output[:,-1]

In [388]:
output = torch.sigmoid(output)

In [389]:
output

tensor([0.5491, 0.7929, 0.2460, 0.7689, 0.3423, 0.3294, 0.3081, 0.2488, 0.3526,
        0.8859, 0.5860, 0.2312, 0.6373, 0.1621, 0.5325, 0.7266])

In [390]:
output = torch.randn(16,100,2)

In [391]:
output = output[:,-1,:]

In [392]:
class_probs = F.softmax(output, dim=-1)

In [393]:
class_probs.shape

torch.Size([16, 2])

In [394]:
class_probs

tensor([[0.7549, 0.2451],
        [0.2537, 0.7463],
        [0.1222, 0.8778],
        [0.3047, 0.6953],
        [0.3182, 0.6818],
        [0.7168, 0.2832],
        [0.8103, 0.1897],
        [0.3765, 0.6235],
        [0.5192, 0.4808],
        [0.6284, 0.3716],
        [0.2558, 0.7442],
        [0.5656, 0.4344],
        [0.1527, 0.8473],
        [0.6987, 0.3013],
        [0.6283, 0.3717],
        [0.0869, 0.9131]])

In [408]:
target_index = torch.ones(class_probs.size(0)).long()

In [409]:
target_index

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [410]:
ans = torch.gather(class_probs, index=target_index)

TypeError: gather() received an invalid combination of arguments - got (Tensor, index=Tensor), but expected one of:
 * (Tensor input, name dim, Tensor index, bool sparse_grad, Tensor out)
 * (Tensor input, int dim, Tensor index, bool sparse_grad, Tensor out)


In [396]:
a = torch.ones(4)

In [397]:
a

tensor([1., 1., 1., 1.])

In [398]:
class_probs.size(0)

16

In [411]:
class_probs

tensor([[0.7549, 0.2451],
        [0.2537, 0.7463],
        [0.1222, 0.8778],
        [0.3047, 0.6953],
        [0.3182, 0.6818],
        [0.7168, 0.2832],
        [0.8103, 0.1897],
        [0.3765, 0.6235],
        [0.5192, 0.4808],
        [0.6284, 0.3716],
        [0.2558, 0.7442],
        [0.5656, 0.4344],
        [0.1527, 0.8473],
        [0.6987, 0.3013],
        [0.6283, 0.3717],
        [0.0869, 0.9131]])

In [412]:
ans = class_probs[:,1:]

In [413]:
ans

tensor([[0.2451],
        [0.7463],
        [0.8778],
        [0.6953],
        [0.6818],
        [0.2832],
        [0.1897],
        [0.6235],
        [0.4808],
        [0.3716],
        [0.7442],
        [0.4344],
        [0.8473],
        [0.3013],
        [0.3717],
        [0.9131]])

In [415]:
ans = ans.squeeze(1)

In [416]:
ans

tensor([0.2451, 0.7463, 0.8778, 0.6953, 0.6818, 0.2832, 0.1897, 0.6235, 0.4808,
        0.3716, 0.7442, 0.4344, 0.8473, 0.3013, 0.3717, 0.9131])

In [478]:
clas = torch.randn(16,1)
clas.shape

torch.Size([16, 1])

In [479]:
clas = clas.view(-1)
clas.shape

torch.Size([16])

In [417]:
import numpy as np

In [418]:
mask = np.zeros(20)

In [419]:
mask


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [420]:
mask[2:] = 1


In [421]:
mask

array([0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [422]:
mask = np.zeros(20)

In [423]:
mask[:] = 1

In [424]:
mask

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [453]:
a = torch.randn(3,4,2)

In [454]:
a

tensor([[[ 0.1959, -0.2011],
         [ 1.0990,  0.5011],
         [ 0.8962,  1.9840],
         [-0.5949, -0.6264]],

        [[ 2.2909,  0.8240],
         [-0.0499, -1.5752],
         [-0.2488,  0.5502],
         [-0.6318, -1.1781]],

        [[-0.6960, -0.2128],
         [-1.0061,  0.9668],
         [ 0.1989, -2.0364],
         [-1.3643, -0.9495]]])

In [455]:
output_loss = a[:,-1:,:]

In [456]:
output_loss

tensor([[[-0.5949, -0.6264]],

        [[-0.6318, -1.1781]],

        [[-1.3643, -0.9495]]])

In [457]:
output_loss.shape

torch.Size([3, 1, 2])

In [461]:
label = torch.randint(0,2,(3,1))

In [462]:
label.shape

torch.Size([3, 1])

In [463]:
label

tensor([[0],
        [0],
        [0]])

In [464]:
label = label.unsqueeze(1)

In [465]:
label

tensor([[[0]],

        [[0]],

        [[0]]])

In [466]:
label.shape

torch.Size([3, 1, 1])

In [470]:
weight = torch.ones(label.size(0),1,1)

In [471]:
weight.shape

torch.Size([3, 1, 1])

In [ ]:
def train_epoch(model, train_iterator, optim, criterion, device="cpu"):
    model.train()

    train_loss = []
    num_corrects = 0
    num_total = 0
    labels = []
    outs = []

    tbar = tqdm(train_iterator)
    for item in tbar:
        x = item[0].to(device).long()
        target_id = item[1].to(device).long()
        ela_x = item[2].to(device).long()
        ela_target = item[3].to(device).long()
        part_x = item[4].to(device).long()
        part_target = item[5].to(device).long()
          
            
        ans_x = item[6].to(device).long()
        label = item[7].to(device).float()        
        weight = item[8].to(device).long()        

        optim.zero_grad()
        output, atten_weight = model(x, target_id, ela_x, ela_target,
                                     part_x, part_target,ans_x)
#         loss = criterion(output, label)
        loss = get_loss(output, label, weight)
        loss.backward()
        optim.step()
#         xm.mark_step()
        train_loss.append(loss.item())

        output = output[:,-1,:]
        label = label[:,-1]
        class_probs = F.softmax(output, dim=-1)
        output = output[:,1:]
        
        max_vals = torch.max(class_probs, dim=-1)
        idx = max_vals[1].tolist()
        pred = torch.LongTensor(idx)
        
        num_corrects = (pred == label).sum().item()
        num_total += len(label)

        labels.extend(label.view(-1).data.cpu().numpy())
        outs.extend(output.view(-1).data.cpu().numpy())

        tbar.set_description('loss - {:.4f}'.format(loss))

    acc = num_corrects / num_total
    auc = roc_auc_score(labels, outs)
    loss = np.mean(train_loss)

    return loss, acc, auc

In [473]:
output = torch.randn(2,4,2)

In [474]:
output.shape

torch.Size([2, 4, 2])

In [475]:
output = output[:,-1,1:]

In [476]:
output.shape

torch.Size([2, 1])

In [ ]:
def evaluate_epoch(model, test_dataloader, criterion, device="cpu"):
    model.eval()
    eval_loss = []
    num_corrects = 0
    num_total = 0
    labels = []
    outs = []
    
    with torch.no_grad():
        for item in tqdm(test_dataloader):
            x = item[0].to(device).long()
            target_id = item[1].to(device).long()
            ela_x = item[2].to(device).long()
            ela_target = item[3].to(device).long()
            part_x = item[4].to(device).long()
            part_target = item[5].to(device).long()
        
            
            ans_x = item[6].to(device).long()
            label = item[7].to(device).float()
#             print("In evaluation x shape is:{}\t taret_id shape is:{}\t label shape is:{}".format(x.shape, target_id.shape,label.shape))
            
            output, atten_weight = model(x, target_id, ela_x, ela_target,
                                         part_x, part_target, ans_x)
            
            output_loss = output[:, -1:,:]
            label_loss = label.unsqueeze(1)
            weights = torch.ones(label.size(0),1,1).to(device).long()        

#             print("Output shape is:{}\tlabel shape is:{}".format(output.shape, label.shape))
            loss = get_loss(output_loss, label_loss,weights)

            eval_loss.append(loss.item())
            
            output = output[:,-1,:]
            label = label[:,-1]
            class_probs = F.softmax(output, dim=-1)
            output = output[:,1:]
        
            max_vals = torch.max(class_probs, dim=-1)
            pred = max_vals[1]
 
            num_corrects += (pred == label).sum().item()
            num_total += len(label)

            labels.extend(label.view(-1).data.cpu().numpy())
            outs.extend(output.view(-1).data.cpu().numpy())

    acc = num_corrects / num_total
#     print("In evaluate labels is:{}\t outs is:{}\t".format(labels, outs))

    auc = roc_auc_score(labels, outs)

    loss = np.mean(eval_loss)   
    
    return loss, acc, auc

In [ ]:
        output = output[:,-1,:]
        label = label[:,-1]
        class_probs = F.softmax(output, dim=-1)
        output = output[:,1:]
        
        max_vals = torch.max(class_probs, dim=-1)
        pred = max_vals[1]
        print("pred is:{}\t pred type is:{}".format(pred, type(pred)))
        print("label is:{}\t label type is:{}".format(label, type(label)))
        
        num_corrects = (pred == label).sum().item()
        num_total += len(label)

In [481]:
            output = output[:,-1,:]
            label = label[:,-1]
            class_probs = F.softmax(output, dim=-1)
            output = output[:,1:]
        
            max_vals = torch.max(class_probs, dim=-1)
            pred = max_vals[1]
 
            num_corrects += (pred == label).sum().item()
            num_total += len(label)

IndexError: too many indices for tensor of dimension 2

In [484]:
2/3

0.6666666666666666

In [482]:
pred = ["c","c","i","i","c","i"]
gold = ["c","i","c","i","c","c"]

In [489]:
total_num = 0
right_num = 0

total_wrong_num = 0
pred_wrong_num = 0

In [490]:
total_num = len(pred)

for i in range(len(pred)):
    if pred[i] == gold[i]:
        right_num += 1
    
    if gold[i] == 'i':
        total_wrong_num += 1
        
        if pred[i] == 'i':
            pred_wrong_num += 1

acc = right_num /total_num
recall = pred_wrong_num / total_wrong_num

print('The total num is:{}, the right num is:{}, the acc is:{}'.format(total_num, right_num, acc))
print('The total wrong num is:{}, the pred wrong num is:{}, the acc is:{}'.format(total_wrong_num, pred_wrong_num, recall))
        
    

The total num is:6, the right num is:3, the acc is:0.5
The total wrong num is:2, the pred wrong num is:1, the acc is:0.5


In [488]:
6/9

0.6666666666666666

In [491]:
class Solution {
    List<List<String>> res = new ArrayList<List<String>>();
    public List<List<String>> solveNQueens(int n) {
        dfs(new int[n], 0, n);
        return res;
    }
    
    public void dfs(int[] pos, int row, int n ){
        if (row == n){
            ArrayList<String> t = getBoard(pos, n);
            res.add(new ArrayList<>(t));
            return;
        }
        
        for (int i = 0; i<n;i++){
            pos[row] = i;
            if(isValid(pos, row, n)){
                dfs(pos, row+1, n);
            }
        }
        
        return;
    }
    
    public Boolean isValid(int[] pos, int r, int n){
        for (int i =0; i<r;i++){
            if(pos[r] == pos[i] || Math.abs(pos[r] -pos[i]) == r-i ){
                return false;
            }
        }
        return true;
        
    }
    
    public ArrayList<String> getBoard(int[] pos, int n){
        ArrayList<String> solution = new ArrayList<String>();
        for(int i =0; i<n;i++){
            StringBuilder sb = new StringBuilder();
            for (int j=0; j<n-1;j++){
                sb.append('.');
            }
            sb.insert(pos[i],'Q');
            solution.add(sb.toString());
        }
        return solution;
    }
}

SyntaxError: invalid syntax (<ipython-input-491-9fa6b3e79135>, line 1)

In [492]:
a = [5,4,8,6,5,3,2]

In [493]:
id(a)

5168650832

In [494]:
r = sorted(a[2:])

In [495]:
a[2:] = r

In [496]:
a

[5, 4, 2, 3, 5, 6, 8]

In [497]:
id(a)

5168650832