In [1]:
import torch

In [2]:
a = torch.tensor([[1,1,1,0,0],[1,1,1,1,0],[1,1,1,1,1]])

In [3]:
trg_pad_idx = 0

In [4]:
src_len = 100

In [6]:
pos = torch.arange(0,100).unsqueeze(0).repeat(4,1)

In [7]:
pos.shape

torch.Size([4, 100])

In [8]:
pos

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         

In [9]:
c = torch.arange(0,100)

In [10]:
c.shape

torch.Size([100])

In [11]:
c

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
c.unsqueeze(0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a = torch.tensor([[1,2,3,4],[1,2,3,4]])

In [19]:
b = a[:,:-1]

In [20]:
b

tensor([[1, 2, 3],
        [1, 2, 3]])

In [21]:
a

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [22]:
output = a.contiguous()

In [23]:
output

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [24]:
output = a.contiguous().view(-1,4)

In [25]:
output

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [27]:
a.shape

torch.Size([2, 4])

In [28]:
output.shape

torch.Size([2, 4])

In [29]:
a = torch.tensor([[1,1,1,0,0],[1,1,1,1,1]])

In [30]:
src_mask = (a != 0)

In [33]:
src_mask

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True]])

In [34]:
src_mask = src_mask.unsqueeze(1)

In [35]:
src_mask

tensor([[[ True,  True,  True, False, False]],

        [[ True,  True,  True,  True,  True]]])

In [36]:
src_mask = src_mask.unsqueeze(2)
src_mask

tensor([[[[ True,  True,  True, False, False]]],


        [[[ True,  True,  True,  True,  True]]]])

In [38]:
src_mask.shape

torch.Size([2, 1, 1, 5])

In [32]:
def make_trg_mask(trg, trg_pad_idx=0):
        
        #trg = [batch size, trg len]
        
    trg_pad_mask = (trg != trg_pad_idx).unsqueeze(1).unsqueeze(2)
        
        #trg_pad_mask = [batch size, 1, 1, trg len]
        
    trg_len = trg.shape[1]
        
    trg_sub_mask = torch.tril(torch.ones((trg_len, trg_len), device = self.device)).bool()
        
        #trg_sub_mask = [trg len, trg len]
            
    trg_mask = trg_pad_mask & trg_sub_mask
        
        #trg_mask = [batch size, 1, trg len, trg len]
        
    return trg_mask


In [49]:
tril = torch.tril(torch.ones((5,5))).bool()

In [50]:
tril.shape

torch.Size([5, 5])

In [51]:
trg_mask = src_mask
trg_mask.shape

torch.Size([2, 1, 1, 5])

In [52]:
fin_trg_mask = trg_mask & tril

In [53]:
fin_trg_mask

tensor([[[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True, False, False]]],


        [[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]]])

In [54]:
trg_mask

tensor([[[[ True,  True,  True, False, False]]],


        [[[ True,  True,  True,  True,  True]]]])

In [55]:
fin_trg_mask.shape

torch.Size([2, 1, 5, 5])

In [61]:
q = torch.rand([16,2,20,4])
k = torch.rand([16,2,20,4])
v = torch.rand([16,2,20,4])

In [62]:
m = torch.matmul(q, k.permute(0, 1, 3, 2))

In [63]:
m.shape

torch.Size([16, 2, 20, 20])

In [64]:
q1 = torch.rand([16,2,20,4])
k1 = torch.rand([16,2,18,4])
v1 = torch.rand([16,2,18,4])
m1 = torch.matmul(q1, k1.permute(0, 1, 3, 2))
m1.shape

torch.Size([16, 2, 20, 18])

In [65]:
loss_fun = torch.nn.CrossEntropyLoss()

In [66]:
input = torch.randn(3,5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

In [67]:
input

tensor([[ 0.2030,  0.6693,  0.4008,  0.6075,  0.0758],
        [-0.6291,  0.8843, -1.9616, -0.4308, -0.3872],
        [-1.2475,  0.2806, -1.1585,  0.2391, -0.1580]], requires_grad=True)

In [68]:
target

tensor([1, 3, 4])

In [69]:
loss = loss_fun(input, target)

In [70]:
loss

tensor(1.6104, grad_fn=<NllLossBackward>)

In [71]:
a = torch.randn([2,4])

In [72]:
a

tensor([[ 0.1210,  0.3557,  0.5862,  0.7488],
        [ 1.1794, -0.2466, -0.4958, -0.3878]])

In [75]:
f = torch.nn.Softmax()

In [76]:
preds = f(a)
preds

/anaconda3/envs/torch1.4/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.1745, 0.2207, 0.2779, 0.3269],
        [0.6112, 0.1468, 0.1145, 0.1275]])

In [77]:
max_vals = torch.max(preds, dim=-1)

In [78]:
max_vals

torch.return_types.max(
values=tensor([0.3269, 0.6112]),
indices=tensor([3, 0]))

In [79]:
probs = max_vals[0].tolist()
probs

[0.3269326090812683, 0.6111830472946167]

In [80]:
idx = max_vals[1].tolist()

In [81]:
idx

[3, 0]

In [82]:
import torch.nn.functional as F


In [83]:
c = F.softmax(a, dim=-1)
c

tensor([[0.1745, 0.2207, 0.2779, 0.3269],
        [0.6112, 0.1468, 0.1145, 0.1275]])

In [84]:
a = torch.randn([64,7,4])

In [86]:
preds = F.softmax(a, dim=-1)

In [87]:
max_vals = torch.max(preds, dim=-1)

In [88]:
max_vals

torch.return_types.max(
values=tensor([[0.4414, 0.6331, 0.4471, 0.5953, 0.3606, 0.6507, 0.5078],
        [0.6413, 0.4161, 0.5297, 0.3431, 0.6247, 0.4151, 0.6829],
        [0.7517, 0.4754, 0.4821, 0.4062, 0.3641, 0.3703, 0.7270],
        [0.4370, 0.5678, 0.5310, 0.5259, 0.6884, 0.4445, 0.3248],
        [0.5530, 0.5714, 0.6498, 0.5435, 0.3256, 0.4513, 0.5422],
        [0.4798, 0.6042, 0.6191, 0.5350, 0.3956, 0.7940, 0.3574],
        [0.4921, 0.4008, 0.5859, 0.4560, 0.3524, 0.4992, 0.4462],
        [0.5242, 0.3591, 0.5735, 0.7373, 0.4701, 0.8272, 0.3484],
        [0.3145, 0.2757, 0.4560, 0.6038, 0.5597, 0.8003, 0.3780],
        [0.4464, 0.3632, 0.6145, 0.5075, 0.7121, 0.5655, 0.4210],
        [0.6513, 0.7177, 0.3740, 0.3068, 0.4346, 0.5750, 0.4812],
        [0.5132, 0.4967, 0.6111, 0.7746, 0.5085, 0.4659, 0.5542],
        [0.3421, 0.4707, 0.5522, 0.4693, 0.4009, 0.4187, 0.4680],
        [0.3462, 0.4723, 0.4131, 0.8475, 0.4040, 0.4067, 0.4529],
        [0.3506, 0.5242, 0.4581, 0.7743, 0.48

In [89]:
probs = max_vals[0].tolist()
probs

[[0.4414104223251343,
  0.6331048011779785,
  0.44713497161865234,
  0.5953177809715271,
  0.36063480377197266,
  0.6507450938224792,
  0.5077533721923828],
 [0.641292154788971,
  0.4161471128463745,
  0.5297022461891174,
  0.3430789113044739,
  0.6246985793113708,
  0.415095716714859,
  0.6828776001930237],
 [0.7517464756965637,
  0.4753861129283905,
  0.48209574818611145,
  0.40617814660072327,
  0.36410513520240784,
  0.37033945322036743,
  0.7270239591598511],
 [0.43704506754875183,
  0.567775547504425,
  0.5310466885566711,
  0.525905966758728,
  0.6884008646011353,
  0.44446805119514465,
  0.3247995674610138],
 [0.552966296672821,
  0.5714285969734192,
  0.6498127579689026,
  0.5435417890548706,
  0.3255971372127533,
  0.4513307213783264,
  0.5421764254570007],
 [0.479844331741333,
  0.6041576862335205,
  0.6190967559814453,
  0.5350333452224731,
  0.3955875039100647,
  0.793952226638794,
  0.3574359714984894],
 [0.49206799268722534,
  0.4008118510246277,
  0.5859078764915466,
  

In [90]:
idx = max_vals[1].tolist()
idx

[[3, 2, 0, 3, 2, 0, 2],
 [1, 2, 3, 1, 1, 1, 0],
 [1, 2, 0, 0, 1, 0, 0],
 [2, 0, 1, 2, 1, 1, 2],
 [3, 3, 2, 2, 3, 0, 0],
 [0, 1, 3, 1, 3, 0, 3],
 [0, 0, 1, 0, 1, 0, 1],
 [3, 1, 0, 0, 3, 3, 2],
 [2, 3, 1, 1, 3, 0, 2],
 [3, 1, 2, 2, 1, 2, 1],
 [1, 1, 1, 3, 1, 0, 2],
 [2, 0, 0, 0, 0, 0, 3],
 [2, 2, 1, 3, 0, 0, 0],
 [1, 2, 2, 0, 3, 1, 1],
 [1, 0, 1, 0, 1, 3, 2],
 [2, 3, 0, 2, 2, 2, 2],
 [0, 0, 2, 2, 1, 0, 3],
 [3, 3, 1, 0, 0, 3, 2],
 [0, 3, 1, 3, 0, 0, 1],
 [2, 2, 2, 2, 3, 1, 3],
 [2, 0, 2, 2, 0, 1, 2],
 [0, 0, 3, 3, 2, 3, 1],
 [1, 3, 0, 1, 2, 2, 0],
 [1, 3, 0, 0, 1, 3, 1],
 [2, 3, 2, 2, 1, 2, 2],
 [1, 1, 2, 2, 0, 1, 3],
 [1, 2, 1, 3, 3, 0, 0],
 [1, 2, 1, 2, 1, 1, 3],
 [3, 0, 0, 2, 2, 1, 0],
 [0, 2, 3, 3, 0, 2, 3],
 [2, 1, 1, 1, 2, 2, 1],
 [3, 1, 3, 1, 2, 0, 1],
 [3, 2, 1, 1, 0, 2, 3],
 [3, 1, 1, 2, 1, 2, 2],
 [3, 1, 3, 0, 1, 2, 2],
 [3, 0, 0, 3, 0, 1, 0],
 [0, 0, 2, 2, 1, 3, 1],
 [0, 2, 3, 3, 3, 0, 3],
 [2, 2, 1, 3, 1, 3, 0],
 [3, 2, 2, 0, 0, 1, 1],
 [1, 2, 2, 0, 0, 2, 2],
 [1, 2, 0, 2, 1,

In [91]:
target = torch.empty([64,7], dtype=torch.long).random_(4)

In [92]:
target

tensor([[3, 1, 3, 0, 2, 2, 1],
        [1, 3, 1, 0, 1, 3, 3],
        [1, 0, 0, 0, 2, 0, 3],
        [3, 0, 2, 1, 0, 2, 2],
        [3, 3, 3, 0, 1, 2, 3],
        [3, 2, 2, 0, 0, 2, 2],
        [2, 1, 3, 0, 0, 2, 0],
        [3, 2, 3, 3, 2, 2, 1],
        [3, 0, 1, 1, 2, 0, 0],
        [0, 0, 1, 3, 1, 3, 0],
        [0, 2, 0, 3, 3, 3, 1],
        [1, 2, 2, 1, 1, 3, 2],
        [1, 2, 1, 0, 0, 0, 0],
        [0, 0, 3, 1, 3, 3, 1],
        [1, 1, 0, 1, 1, 2, 2],
        [3, 1, 2, 2, 1, 3, 1],
        [2, 2, 2, 2, 0, 2, 1],
        [0, 2, 3, 2, 2, 1, 1],
        [2, 2, 0, 3, 0, 1, 1],
        [1, 1, 3, 0, 3, 0, 1],
        [2, 3, 0, 3, 1, 0, 3],
        [0, 2, 3, 1, 2, 2, 3],
        [2, 1, 0, 0, 0, 3, 2],
        [3, 1, 3, 0, 3, 2, 1],
        [3, 0, 2, 2, 1, 2, 2],
        [1, 1, 0, 2, 3, 0, 1],
        [2, 2, 0, 2, 3, 2, 2],
        [3, 0, 0, 3, 3, 2, 1],
        [3, 0, 2, 3, 1, 0, 2],
        [3, 2, 0, 0, 0, 0, 0],
        [3, 1, 1, 3, 2, 0, 0],
        [1, 1, 3, 2, 3, 0, 3],
        

In [96]:
out = torch.tensor([[1,1,0,0],[0,1,0,1]])
trg = torch.tensor([[1,1,0,1],[0,1,0,1]])

In [97]:
right_num = (out==trg).sum().item()
right_num

7

In [98]:
trg_id = torch.tensor([[2,3,0,1],[1,1,1,0]])

In [101]:
out_class = out[:,-1:]
out_class

tensor([[0],
        [1]])

In [103]:
trg_class = trg[:,-1:]
trg_class

tensor([[1],
        [1]])

In [104]:
right_num = (out_class == trg_class).sum().item()

In [105]:
right_num

1

In [106]:
total_num = len(trg_class)

In [107]:
total_num

2

In [108]:
c = max_vals[1]

In [109]:
c


tensor([[3, 2, 0, 3, 2, 0, 2],
        [1, 2, 3, 1, 1, 1, 0],
        [1, 2, 0, 0, 1, 0, 0],
        [2, 0, 1, 2, 1, 1, 2],
        [3, 3, 2, 2, 3, 0, 0],
        [0, 1, 3, 1, 3, 0, 3],
        [0, 0, 1, 0, 1, 0, 1],
        [3, 1, 0, 0, 3, 3, 2],
        [2, 3, 1, 1, 3, 0, 2],
        [3, 1, 2, 2, 1, 2, 1],
        [1, 1, 1, 3, 1, 0, 2],
        [2, 0, 0, 0, 0, 0, 3],
        [2, 2, 1, 3, 0, 0, 0],
        [1, 2, 2, 0, 3, 1, 1],
        [1, 0, 1, 0, 1, 3, 2],
        [2, 3, 0, 2, 2, 2, 2],
        [0, 0, 2, 2, 1, 0, 3],
        [3, 3, 1, 0, 0, 3, 2],
        [0, 3, 1, 3, 0, 0, 1],
        [2, 2, 2, 2, 3, 1, 3],
        [2, 0, 2, 2, 0, 1, 2],
        [0, 0, 3, 3, 2, 3, 1],
        [1, 3, 0, 1, 2, 2, 0],
        [1, 3, 0, 0, 1, 3, 1],
        [2, 3, 2, 2, 1, 2, 2],
        [1, 1, 2, 2, 0, 1, 3],
        [1, 2, 1, 3, 3, 0, 0],
        [1, 2, 1, 2, 1, 1, 3],
        [3, 0, 0, 2, 2, 1, 0],
        [0, 2, 3, 3, 0, 2, 3],
        [2, 1, 1, 1, 2, 2, 1],
        [3, 1, 3, 1, 2, 0, 1],
        

In [111]:
out_id = c[:,-1:]

In [112]:
out_id

tensor([[2],
        [0],
        [0],
        [2],
        [0],
        [3],
        [1],
        [2],
        [2],
        [1],
        [2],
        [3],
        [0],
        [1],
        [2],
        [2],
        [3],
        [2],
        [1],
        [3],
        [2],
        [1],
        [0],
        [1],
        [2],
        [3],
        [0],
        [3],
        [0],
        [3],
        [1],
        [1],
        [3],
        [2],
        [2],
        [0],
        [1],
        [3],
        [0],
        [1],
        [2],
        [3],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [2],
        [0],
        [0],
        [0],
        [1],
        [2],
        [3],
        [1]])

In [115]:
c = torch.tensor([[2,3],[4,5]])

In [116]:
c

tensor([[2, 3],
        [4, 5]])

In [117]:
d = c.shape[-1]

In [118]:
d

2

In [119]:
a = torch.tensor([[2,3],[3,2]])

In [120]:
trg = torch.tensor([[1,0],[1,1]])

In [122]:
loss_func = torch.nn.CrossEntropyLoss()

In [123]:
trg_id = trg[:,-1:]

In [124]:
trg_id

tensor([[0],
        [1]])

In [125]:
output = torch.randn([2,3,2])

In [126]:
output

tensor([[[ 0.0959, -1.0810],
         [ 0.8180,  0.0406],
         [-0.4635, -2.3926]],

        [[-1.8298,  1.0813],
         [-0.3038,  2.0032],
         [ 0.2218,  0.1423]]])

In [127]:
output_trg = output[:,-1:,:]

In [128]:
output_trg

tensor([[[-0.4635, -2.3926]],

        [[ 0.2218,  0.1423]]])

In [129]:
output_trg.shape

torch.Size([2, 1, 2])

In [131]:
output_trg2 = output_trg.squeeze(1)

In [132]:
output_trg2.shape

torch.Size([2, 2])

In [133]:
loss = loss_func(output_trg2, trg_id)

RuntimeError: 1D target tensor expected, multi-target not supported

In [134]:
output_trg2

tensor([[-0.4635, -2.3926],
        [ 0.2218,  0.1423]])

In [136]:
trg_id

tensor([[0],
        [1]])

In [137]:
trg_id.shape

torch.Size([2, 1])

In [138]:
output_trg2.shape

torch.Size([2, 2])

In [139]:
trg_id2 = trg_id.view(-1)

In [140]:
trg_id2

tensor([0, 1])

In [141]:
loss = loss_func(output_trg2, trg_id2)

In [142]:
loss

tensor(0.4347)