In [1]:
import torch

In [2]:
a = torch.tensor([[1,1,1,0,0],[1,1,1,1,0],[1,1,1,1,1]])

In [3]:
trg_pad_idx = 0

In [4]:
src_len = 100

In [6]:
pos = torch.arange(0,100).unsqueeze(0).repeat(4,1)

In [7]:
pos.shape

torch.Size([4, 100])

In [8]:
pos

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         

In [9]:
c = torch.arange(0,100)

In [10]:
c.shape

torch.Size([100])

In [11]:
c

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
c.unsqueeze(0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a = torch.tensor([[1,2,3,4],[1,2,3,4]])

In [19]:
b = a[:,:-1]

In [20]:
b

tensor([[1, 2, 3],
        [1, 2, 3]])

In [21]:
a

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [22]:
output = a.contiguous()

In [23]:
output

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [24]:
output = a.contiguous().view(-1,4)

In [25]:
output

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [27]:
a.shape

torch.Size([2, 4])

In [28]:
output.shape

torch.Size([2, 4])

In [29]:
a = torch.tensor([[1,1,1,0,0],[1,1,1,1,1]])

In [30]:
src_mask = (a != 0)

In [33]:
src_mask

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True]])

In [34]:
src_mask = src_mask.unsqueeze(1)

In [35]:
src_mask

tensor([[[ True,  True,  True, False, False]],

        [[ True,  True,  True,  True,  True]]])

In [36]:
src_mask = src_mask.unsqueeze(2)
src_mask

tensor([[[[ True,  True,  True, False, False]]],


        [[[ True,  True,  True,  True,  True]]]])

In [38]:
src_mask.shape

torch.Size([2, 1, 1, 5])

In [32]:
def make_trg_mask(trg, trg_pad_idx=0):
        
        #trg = [batch size, trg len]
        
    trg_pad_mask = (trg != trg_pad_idx).unsqueeze(1).unsqueeze(2)
        
        #trg_pad_mask = [batch size, 1, 1, trg len]
        
    trg_len = trg.shape[1]
        
    trg_sub_mask = torch.tril(torch.ones((trg_len, trg_len), device = self.device)).bool()
        
        #trg_sub_mask = [trg len, trg len]
            
    trg_mask = trg_pad_mask & trg_sub_mask
        
        #trg_mask = [batch size, 1, trg len, trg len]
        
    return trg_mask


In [49]:
tril = torch.tril(torch.ones((5,5))).bool()

In [50]:
tril.shape

torch.Size([5, 5])

In [51]:
trg_mask = src_mask
trg_mask.shape

torch.Size([2, 1, 1, 5])

In [52]:
fin_trg_mask = trg_mask & tril

In [53]:
fin_trg_mask

tensor([[[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True, False, False]]],


        [[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]]])

In [54]:
trg_mask

tensor([[[[ True,  True,  True, False, False]]],


        [[[ True,  True,  True,  True,  True]]]])

In [55]:
fin_trg_mask.shape

torch.Size([2, 1, 5, 5])

In [61]:
q = torch.rand([16,2,20,4])
k = torch.rand([16,2,20,4])
v = torch.rand([16,2,20,4])

In [62]:
m = torch.matmul(q, k.permute(0, 1, 3, 2))

In [63]:
m.shape

torch.Size([16, 2, 20, 20])

In [64]:
q1 = torch.rand([16,2,20,4])
k1 = torch.rand([16,2,18,4])
v1 = torch.rand([16,2,18,4])
m1 = torch.matmul(q1, k1.permute(0, 1, 3, 2))
m1.shape

torch.Size([16, 2, 20, 18])

In [65]:
loss_fun = torch.nn.CrossEntropyLoss()

In [66]:
input = torch.randn(3,5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

In [67]:
input

tensor([[ 0.2030,  0.6693,  0.4008,  0.6075,  0.0758],
        [-0.6291,  0.8843, -1.9616, -0.4308, -0.3872],
        [-1.2475,  0.2806, -1.1585,  0.2391, -0.1580]], requires_grad=True)

In [68]:
target

tensor([1, 3, 4])

In [69]:
loss = loss_fun(input, target)

In [70]:
loss

tensor(1.6104, grad_fn=<NllLossBackward>)

In [71]:
a = torch.randn([2,4])

In [72]:
a

tensor([[ 0.1210,  0.3557,  0.5862,  0.7488],
        [ 1.1794, -0.2466, -0.4958, -0.3878]])

In [75]:
f = torch.nn.Softmax()

In [76]:
preds = f(a)
preds

/anaconda3/envs/torch1.4/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.1745, 0.2207, 0.2779, 0.3269],
        [0.6112, 0.1468, 0.1145, 0.1275]])

In [77]:
max_vals = torch.max(preds, dim=-1)

In [78]:
max_vals

torch.return_types.max(
values=tensor([0.3269, 0.6112]),
indices=tensor([3, 0]))

In [79]:
probs = max_vals[0].tolist()
probs

[0.3269326090812683, 0.6111830472946167]

In [80]:
idx = max_vals[1].tolist()

In [81]:
idx

[3, 0]

In [82]:
import torch.nn.functional as F


In [83]:
c = F.softmax(a, dim=-1)
c

tensor([[0.1745, 0.2207, 0.2779, 0.3269],
        [0.6112, 0.1468, 0.1145, 0.1275]])

In [84]:
a = torch.randn([64,7,4])

In [86]:
preds = F.softmax(a, dim=-1)

In [87]:
max_vals = torch.max(preds, dim=-1)

In [88]:
max_vals

torch.return_types.max(
values=tensor([[0.4414, 0.6331, 0.4471, 0.5953, 0.3606, 0.6507, 0.5078],
        [0.6413, 0.4161, 0.5297, 0.3431, 0.6247, 0.4151, 0.6829],
        [0.7517, 0.4754, 0.4821, 0.4062, 0.3641, 0.3703, 0.7270],
        [0.4370, 0.5678, 0.5310, 0.5259, 0.6884, 0.4445, 0.3248],
        [0.5530, 0.5714, 0.6498, 0.5435, 0.3256, 0.4513, 0.5422],
        [0.4798, 0.6042, 0.6191, 0.5350, 0.3956, 0.7940, 0.3574],
        [0.4921, 0.4008, 0.5859, 0.4560, 0.3524, 0.4992, 0.4462],
        [0.5242, 0.3591, 0.5735, 0.7373, 0.4701, 0.8272, 0.3484],
        [0.3145, 0.2757, 0.4560, 0.6038, 0.5597, 0.8003, 0.3780],
        [0.4464, 0.3632, 0.6145, 0.5075, 0.7121, 0.5655, 0.4210],
        [0.6513, 0.7177, 0.3740, 0.3068, 0.4346, 0.5750, 0.4812],
        [0.5132, 0.4967, 0.6111, 0.7746, 0.5085, 0.4659, 0.5542],
        [0.3421, 0.4707, 0.5522, 0.4693, 0.4009, 0.4187, 0.4680],
        [0.3462, 0.4723, 0.4131, 0.8475, 0.4040, 0.4067, 0.4529],
        [0.3506, 0.5242, 0.4581, 0.7743, 0.48

In [89]:
probs = max_vals[0].tolist()
probs

[[0.4414104223251343,
  0.6331048011779785,
  0.44713497161865234,
  0.5953177809715271,
  0.36063480377197266,
  0.6507450938224792,
  0.5077533721923828],
 [0.641292154788971,
  0.4161471128463745,
  0.5297022461891174,
  0.3430789113044739,
  0.6246985793113708,
  0.415095716714859,
  0.6828776001930237],
 [0.7517464756965637,
  0.4753861129283905,
  0.48209574818611145,
  0.40617814660072327,
  0.36410513520240784,
  0.37033945322036743,
  0.7270239591598511],
 [0.43704506754875183,
  0.567775547504425,
  0.5310466885566711,
  0.525905966758728,
  0.6884008646011353,
  0.44446805119514465,
  0.3247995674610138],
 [0.552966296672821,
  0.5714285969734192,
  0.6498127579689026,
  0.5435417890548706,
  0.3255971372127533,
  0.4513307213783264,
  0.5421764254570007],
 [0.479844331741333,
  0.6041576862335205,
  0.6190967559814453,
  0.5350333452224731,
  0.3955875039100647,
  0.793952226638794,
  0.3574359714984894],
 [0.49206799268722534,
  0.4008118510246277,
  0.5859078764915466,
  

In [90]:
idx = max_vals[1].tolist()
idx

[[3, 2, 0, 3, 2, 0, 2],
 [1, 2, 3, 1, 1, 1, 0],
 [1, 2, 0, 0, 1, 0, 0],
 [2, 0, 1, 2, 1, 1, 2],
 [3, 3, 2, 2, 3, 0, 0],
 [0, 1, 3, 1, 3, 0, 3],
 [0, 0, 1, 0, 1, 0, 1],
 [3, 1, 0, 0, 3, 3, 2],
 [2, 3, 1, 1, 3, 0, 2],
 [3, 1, 2, 2, 1, 2, 1],
 [1, 1, 1, 3, 1, 0, 2],
 [2, 0, 0, 0, 0, 0, 3],
 [2, 2, 1, 3, 0, 0, 0],
 [1, 2, 2, 0, 3, 1, 1],
 [1, 0, 1, 0, 1, 3, 2],
 [2, 3, 0, 2, 2, 2, 2],
 [0, 0, 2, 2, 1, 0, 3],
 [3, 3, 1, 0, 0, 3, 2],
 [0, 3, 1, 3, 0, 0, 1],
 [2, 2, 2, 2, 3, 1, 3],
 [2, 0, 2, 2, 0, 1, 2],
 [0, 0, 3, 3, 2, 3, 1],
 [1, 3, 0, 1, 2, 2, 0],
 [1, 3, 0, 0, 1, 3, 1],
 [2, 3, 2, 2, 1, 2, 2],
 [1, 1, 2, 2, 0, 1, 3],
 [1, 2, 1, 3, 3, 0, 0],
 [1, 2, 1, 2, 1, 1, 3],
 [3, 0, 0, 2, 2, 1, 0],
 [0, 2, 3, 3, 0, 2, 3],
 [2, 1, 1, 1, 2, 2, 1],
 [3, 1, 3, 1, 2, 0, 1],
 [3, 2, 1, 1, 0, 2, 3],
 [3, 1, 1, 2, 1, 2, 2],
 [3, 1, 3, 0, 1, 2, 2],
 [3, 0, 0, 3, 0, 1, 0],
 [0, 0, 2, 2, 1, 3, 1],
 [0, 2, 3, 3, 3, 0, 3],
 [2, 2, 1, 3, 1, 3, 0],
 [3, 2, 2, 0, 0, 1, 1],
 [1, 2, 2, 0, 0, 2, 2],
 [1, 2, 0, 2, 1,

In [91]:
target = torch.empty([64,7], dtype=torch.long).random_(4)

In [92]:
target

tensor([[3, 1, 3, 0, 2, 2, 1],
        [1, 3, 1, 0, 1, 3, 3],
        [1, 0, 0, 0, 2, 0, 3],
        [3, 0, 2, 1, 0, 2, 2],
        [3, 3, 3, 0, 1, 2, 3],
        [3, 2, 2, 0, 0, 2, 2],
        [2, 1, 3, 0, 0, 2, 0],
        [3, 2, 3, 3, 2, 2, 1],
        [3, 0, 1, 1, 2, 0, 0],
        [0, 0, 1, 3, 1, 3, 0],
        [0, 2, 0, 3, 3, 3, 1],
        [1, 2, 2, 1, 1, 3, 2],
        [1, 2, 1, 0, 0, 0, 0],
        [0, 0, 3, 1, 3, 3, 1],
        [1, 1, 0, 1, 1, 2, 2],
        [3, 1, 2, 2, 1, 3, 1],
        [2, 2, 2, 2, 0, 2, 1],
        [0, 2, 3, 2, 2, 1, 1],
        [2, 2, 0, 3, 0, 1, 1],
        [1, 1, 3, 0, 3, 0, 1],
        [2, 3, 0, 3, 1, 0, 3],
        [0, 2, 3, 1, 2, 2, 3],
        [2, 1, 0, 0, 0, 3, 2],
        [3, 1, 3, 0, 3, 2, 1],
        [3, 0, 2, 2, 1, 2, 2],
        [1, 1, 0, 2, 3, 0, 1],
        [2, 2, 0, 2, 3, 2, 2],
        [3, 0, 0, 3, 3, 2, 1],
        [3, 0, 2, 3, 1, 0, 2],
        [3, 2, 0, 0, 0, 0, 0],
        [3, 1, 1, 3, 2, 0, 0],
        [1, 1, 3, 2, 3, 0, 3],
        

In [96]:
out = torch.tensor([[1,1,0,0],[0,1,0,1]])
trg = torch.tensor([[1,1,0,1],[0,1,0,1]])

In [97]:
right_num = (out==trg).sum().item()
right_num

7

In [98]:
trg_id = torch.tensor([[2,3,0,1],[1,1,1,0]])

In [101]:
out_class = out[:,-1:]
out_class

tensor([[0],
        [1]])

In [103]:
trg_class = trg[:,-1:]
trg_class

tensor([[1],
        [1]])

In [104]:
right_num = (out_class == trg_class).sum().item()

In [105]:
right_num

1

In [106]:
total_num = len(trg_class)

In [107]:
total_num

2

In [108]:
c = max_vals[1]

In [109]:
c


tensor([[3, 2, 0, 3, 2, 0, 2],
        [1, 2, 3, 1, 1, 1, 0],
        [1, 2, 0, 0, 1, 0, 0],
        [2, 0, 1, 2, 1, 1, 2],
        [3, 3, 2, 2, 3, 0, 0],
        [0, 1, 3, 1, 3, 0, 3],
        [0, 0, 1, 0, 1, 0, 1],
        [3, 1, 0, 0, 3, 3, 2],
        [2, 3, 1, 1, 3, 0, 2],
        [3, 1, 2, 2, 1, 2, 1],
        [1, 1, 1, 3, 1, 0, 2],
        [2, 0, 0, 0, 0, 0, 3],
        [2, 2, 1, 3, 0, 0, 0],
        [1, 2, 2, 0, 3, 1, 1],
        [1, 0, 1, 0, 1, 3, 2],
        [2, 3, 0, 2, 2, 2, 2],
        [0, 0, 2, 2, 1, 0, 3],
        [3, 3, 1, 0, 0, 3, 2],
        [0, 3, 1, 3, 0, 0, 1],
        [2, 2, 2, 2, 3, 1, 3],
        [2, 0, 2, 2, 0, 1, 2],
        [0, 0, 3, 3, 2, 3, 1],
        [1, 3, 0, 1, 2, 2, 0],
        [1, 3, 0, 0, 1, 3, 1],
        [2, 3, 2, 2, 1, 2, 2],
        [1, 1, 2, 2, 0, 1, 3],
        [1, 2, 1, 3, 3, 0, 0],
        [1, 2, 1, 2, 1, 1, 3],
        [3, 0, 0, 2, 2, 1, 0],
        [0, 2, 3, 3, 0, 2, 3],
        [2, 1, 1, 1, 2, 2, 1],
        [3, 1, 3, 1, 2, 0, 1],
        

In [111]:
out_id = c[:,-1:]

In [112]:
out_id

tensor([[2],
        [0],
        [0],
        [2],
        [0],
        [3],
        [1],
        [2],
        [2],
        [1],
        [2],
        [3],
        [0],
        [1],
        [2],
        [2],
        [3],
        [2],
        [1],
        [3],
        [2],
        [1],
        [0],
        [1],
        [2],
        [3],
        [0],
        [3],
        [0],
        [3],
        [1],
        [1],
        [3],
        [2],
        [2],
        [0],
        [1],
        [3],
        [0],
        [1],
        [2],
        [3],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [2],
        [0],
        [0],
        [0],
        [1],
        [2],
        [3],
        [1]])

In [115]:
c = torch.tensor([[2,3],[4,5]])

In [116]:
c

tensor([[2, 3],
        [4, 5]])

In [117]:
d = c.shape[-1]

In [118]:
d

2

In [119]:
a = torch.tensor([[2,3],[3,2]])

In [120]:
trg = torch.tensor([[1,0],[1,1]])

In [122]:
loss_func = torch.nn.CrossEntropyLoss()

In [123]:
trg_id = trg[:,-1:]

In [124]:
trg_id

tensor([[0],
        [1]])

In [125]:
output = torch.randn([2,3,2])

In [126]:
output

tensor([[[ 0.0959, -1.0810],
         [ 0.8180,  0.0406],
         [-0.4635, -2.3926]],

        [[-1.8298,  1.0813],
         [-0.3038,  2.0032],
         [ 0.2218,  0.1423]]])

In [127]:
output_trg = output[:,-1:,:]

In [128]:
output_trg

tensor([[[-0.4635, -2.3926]],

        [[ 0.2218,  0.1423]]])

In [129]:
output_trg.shape

torch.Size([2, 1, 2])

In [131]:
output_trg2 = output_trg.squeeze(1)

In [132]:
output_trg2.shape

torch.Size([2, 2])

In [133]:
loss = loss_func(output_trg2, trg_id)

RuntimeError: 1D target tensor expected, multi-target not supported

In [134]:
output_trg2

tensor([[-0.4635, -2.3926],
        [ 0.2218,  0.1423]])

In [136]:
trg_id

tensor([[0],
        [1]])

In [137]:
trg_id.shape

torch.Size([2, 1])

In [138]:
output_trg2.shape

torch.Size([2, 2])

In [139]:
trg_id2 = trg_id.view(-1)

In [140]:
trg_id2

tensor([0, 1])

In [141]:
loss = loss_func(output_trg2, trg_id2)

In [142]:
loss

tensor(0.4347)

In [1]:
def get_data_for_train(train_user, seq_len):
    all_ques_seq = []
    all_ans_seq = []
    all_parts_seq = []
    all_ela_seq = []
    
    for row in train_user.itertuples():
        q_ids = getattr(row, 'question_id').strip().split(',')
        ans_ids = getattr(row, 'answered_correctly').strip().split(',')
        part_ids = getattr(row, 'part').strip().split(',')
        ela_ids = getattr(row, 'prior_question_elapsed_time').strip().split(',')
        
        assert len(q_ids) == len(ans_ids) == len(part_ids) == len(ela_ids)
        for target_index in range(0, len(q_ids)):
            q_ids_seq = q_ids[:target_index+1]
            ans_ids_seq = ans_ids[:target_index+1]
            part_ids_seq = part_ids[:target_index+1]
            ela_ids_seq = ela_ids[:target_index+1]
            
            length = len(q_ids_seq)
            if length >= seq_len:
                q_ids_seq = q_ids_seq[-seq_len:]
                ans_ids_seq = ans_ids_seq[-seq_len:]
                part_ids_seq = part_ids_seq[-seq_len:]
                ela_ids_seq = ela_ids_seq[-seq_len:]  
                
                pad_counts = 0
            else:
                pad_counts = seq_len - length
            
            q_ids_seq = [int(float(e)) for e in q_ids_seq]
            ans_ids_seq = [int(float(e)) for e in ans_ids_seq]
            part_ids_seq = [int(float(e)) for e in part_ids_seq]
            ela_ids_seq = [int(float(e)) for e in ela_ids_seq]
            
            q_ids_seq = [13523]*pad_counts + q_ids_seq
            # question用13523表示padding位
            ans_ids_seq = [2]*pad_counts + [3] + ans_ids_seq
            # ans用2表示padding位
            # ans因为是输入到decoder中，所以需要一个起始符号，这里选择3作为其实符号，也就是句子序列中的bos的作用
            part_ids_seq = [8]*pad_counts + part_ids_seq
            # part用8来表示padding位
            ela_ids_seq = [301]*pad_counts + ela_ids_seq
            # ela用301来表示padding位
#             print("q_ids length is:{}\n ans_ids length is:{}\n part length is:{}\n ela_ids length is:{}".format(len(q_ids_seq),len(ans_ids_seq),len(part_ids_seq),len(ela_ids_seq)))
            all_ques_seq.append(q_ids_seq)
            all_ans_seq.append(ans_ids_seq)
            all_parts_seq.append(part_ids_seq)
            all_ela_seq.append(ela_ids_seq)
    return torch.LongTensor(all_ques_seq),\
        torch.LongTensor(all_ans_seq),\
        torch.LongTensor(all_parts_seq),\
        torch.LongTensor(all_ela_seq)
            
            

In [3]:
import torch

In [25]:
src = torch.tensor([[[2,1,1,1],[2,1,1,1],[1,1,1,1]]])

In [26]:
trg = torch.tensor([[[1,2,3,1]]])

In [27]:
src.shape

torch.Size([1, 3, 4])

In [28]:
trg.shape

torch.Size([1, 1, 4])

In [29]:
mask = torch.tensor([0,1,1])

In [30]:
def get_attention_result(src, trg, mask):
#     src = src.view(1,-1,2,2).permute(0,2,1,3)
#     trg = trg.view(1,-1,2,2).permute(0,2,1,3)
    energy = torch.matmul(src,trg)
    
    print("src shape:{}\nenergy shape:{}".format(src.shape,energy.shape))
    

In [31]:
get_attention_result(src, trg, mask)

RuntimeError: Expected tensor to have size 4 at dimension 1, but got size 1 for argument #2 'batch2' (while checking arguments for bmm)

In [32]:
attention = torch.bmm(src, trg.transpose(1,2))

In [33]:
attention

tensor([[[8],
         [8],
         [7]]])

In [34]:
attention.shape

torch.Size([1, 3, 1])

In [73]:

m = torch.nn.AvgPool1d(100)

In [74]:
input = torch.randn(2,100,256)

In [75]:
input

tensor([[[ 0.4736,  0.9023, -0.8562,  ..., -0.6136,  0.0767,  0.1503],
         [ 2.3009,  1.6146, -0.5615,  ...,  1.8651,  1.1419, -0.4475],
         [-0.1787, -0.3650,  0.8095,  ...,  1.5195,  0.3976, -0.9619],
         ...,
         [-1.0840, -0.3249,  0.6389,  ...,  0.8220,  0.6150,  0.5288],
         [ 1.1683,  1.5250, -0.6610,  ..., -0.9006, -0.2188,  1.3951],
         [ 1.0423,  1.0118,  0.1217,  ...,  0.3330, -0.0460, -1.2584]],

        [[-0.0054, -0.2634, -0.7244,  ...,  1.4888,  0.3083, -0.5705],
         [ 0.9709, -1.9745,  1.1256,  ...,  0.0600, -0.7063,  0.9467],
         [ 1.7755, -0.2479, -0.3239,  ..., -0.8077, -0.2675, -0.4325],
         ...,
         [-1.0190,  0.0802,  0.1475,  ..., -0.1744, -0.2505, -2.6924],
         [ 0.0557, -0.1746, -0.8300,  ..., -1.4583,  0.4239,  1.5854],
         [ 0.4634,  0.0186, -0.2102,  ...,  0.0725,  0.6696, -0.3163]]])

In [76]:
res = m(input.permute(0,2,1)).permute(0,2,1)

In [77]:
res.shape

torch.Size([2, 1, 256])

In [81]:
a = torch.tensor([[[1,1,1,1],[3,3,3,3]]])

In [82]:
m = torch.nn.AvgPool1d(2)

In [83]:
res = m(a.permute(0,2,1)).permute(0,2,1)

In [84]:
res

tensor([[[2, 2, 2, 2]]])

In [85]:
a = torch.randn(2,1,2)

In [86]:
a.shape

torch.Size([2, 1, 2])

In [87]:
c = a.unsqueeze(1)

In [88]:
c.shape

torch.Size([2, 1, 1, 2])

In [89]:
c = a.squeeze(1)

In [90]:
c.shape

torch.Size([2, 2])

In [94]:
import torch.nn.functional as F


In [96]:
a = torch.randn(2,2)

In [97]:
a

tensor([[-1.2318,  0.4170],
        [-0.2039,  1.3339]])

In [92]:
trg = torch.tensor([[1],[1]])

In [98]:
preds = F.softmax(a, dim=-1)

In [99]:
preds

tensor([[0.1613, 0.8387],
        [0.1769, 0.8231]])

In [100]:
preds_ind = (preds >= 0.5).long()

In [101]:
preds_ind

tensor([[0, 1],
        [0, 1]])

In [114]:
preds

tensor([[0.1613, 0.8387],
        [0.1769, 0.8231]])

In [115]:
max_res = torch.max(preds, dim=1)

In [116]:
max_res

torch.return_types.max(
values=tensor([0.8387, 0.8231]),
indices=tensor([1, 1]))

In [106]:
ind = max_res[1]

In [107]:
ind

tensor([1, 0])

In [108]:
trg = trg.contiguous().view(-1)

In [109]:
trg

tensor([1, 1])

In [110]:
num = (ind == trg).sum().item()

In [111]:
num

1

In [112]:
s = len(trg)

In [113]:
s

2

In [117]:
a = torch.randn(2,1,3)

In [118]:
a

tensor([[[-0.4080,  1.5388,  1.1190]],

        [[ 0.3770, -0.9925, -0.4448]]])

In [119]:
c = a.squeeze(1)

In [120]:
c.shape

torch.Size([2, 3])

In [121]:
def _get_position_index( question_id):
        """
        [0, 0, 0, 4, 12] -> [0, 0, 0, 1, 2]
        """
        batch_size = question_id.shape[0]
        position_indices = []
        for i in range(batch_size):
            non_padding_num = (question_id[i] != PAD_INDEX).sum(-1).item()
            position_index = [0] * (ARGS.seq_size - non_padding_num) + list(range(1, non_padding_num+1))
            position_indices.append(position_index)
        return torch.tensor(position_indices, dtype=int).to(ARGS.device)

In [122]:
def get_position_index(mask):
    batch_size = mask.shape[0]
    position_indices = []
    for i in range(batch_size):
        non_pad_num = (mask[i] != 0).sum(-1).item()
        pos_index = [0]*(100 - non_pad_num) + list(1, non_pad_num+1)
        position_indices.append(pos_index)
    return torch.tensor(position_indices, dtype=int)

In [123]:
pad_counts = 8
length = 92


In [124]:
pos_ids = [0]*pad_counts + list(range(1,length+1))


In [126]:
len(pos_ids)

100

In [127]:
a = [0,0,0,0,1,2,3,4,5]

In [ ]:
def get_position(nums, pad_index):
    seq_size = 100
    non_pad_num = (nums)

In [131]:
import numpy as np

In [133]:
x = np.zeros(99,dtype=int)
x
len(x)

99

In [139]:
q_ = [12,1,3,4,5,6,7,8,89,9]

In [152]:
x = q_[:].copy()

In [141]:
x

[12, 1, 3, 4, 5, 6, 7, 8, 89]

In [148]:
qa_ = [1,1,1,1,0,0,1,1,0,1]
len(qa_)

10

In [144]:
q = np.zeros(10, dtype=int)

In [145]:
q[:] = q_[:]

In [146]:
qa = np.zeros(10,dtype=int)

In [149]:
qa[:] = qa_[:]

In [150]:
x

[12, 1, 3, 4, 5, 6, 7, 8, 89]

In [153]:
len(x)

10

In [154]:
x += (qa[:] == 1) * 13254

In [155]:
x

array([13266, 13255, 13257, 13258,     5,     6, 13261, 13262,    89,
       13263])

In [156]:
a = [1,2,3]

In [157]:
b = a[-100:]

In [158]:
b

[1, 2, 3]

In [159]:

def future_mask(seq_length):
    future_mask = np.triu(np.ones((seq_length, seq_length)), k=1).astype('bool')
    return torch.from_numpy(future_mask)

In [160]:
a = future_mask(8)

In [161]:
a

tensor([[False,  True,  True,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False]])

In [163]:
import pandas as pd

In [165]:
question_df = pd.read_csv('/Users/hesu/Documents/KT/riiid/questions.csv')
question_df.head(10)

question_id  bundle_id  correct_answer  part            tags
0            0          0               0     1   51 131 162 38
1            1          1               1     1       131 36 81
2            2          2               0     1  131 101 162 92
3            3          3               0     1  131 149 162 29
4            4          4               3     1    131 5 162 38
5            5          5               2     1  131 149 162 81
6            6          6               2     1    10 94 162 92
7            7          7               0     1   61 110 162 29
8            8          8               3     1   131 13 162 92
9            9          9               3     1       10 164 81

In [166]:
question_df['part'].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [167]:
question_df['bundle_id'].unique()

array([    0,     1,     2, ..., 13520, 13521, 13522])

In [168]:
question_df['part'].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [169]:
question_df['tags'].unique()

array(['51 131 162 38', '131 36 81', '131 101 162 92', ..., '136 92 59',
       '106 81 59', '157 169 92'], dtype=object)

In [171]:
import transformers

In [172]:
from transformers import BertTokenizer

In [173]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [174]:
prompt_text = ['<BOS> Keeping the Secret of Genetic Testing',
    '<BOS> What is genetic risk ?',
    '<BOS> How much a genetic change tells us about your chance of developing a disorder is not alway    s clear .']

In [175]:
encodings_dict = tokenizer.batch_encode_plus(prompt_text, 
                                             max_length=40,pad_to_max_length=True,
                                             add_special_tokens=True,return_tensors="pt")

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/anaconda3/envs/torch1.4/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2022: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [176]:
encodings_dict

{'input_ids': tensor([[ 101, 1026, 8945, 2015, 1028, 4363, 1996, 3595, 1997, 7403, 5604,  102,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 101, 1026, 8945, 2015, 1028, 2054, 2003, 7403, 3891, 1029,  102,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 101, 1026, 8945, 2015, 1028, 2129, 2172, 1037, 7403, 2689, 4136, 2149,
         2055, 2115, 3382, 1997, 4975, 1037, 8761, 2003, 2025, 2632, 4576, 1055,
         3154, 1012,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [177]:
input_ids = encodings_dict["input_ids"]

In [178]:
attn_mask = encodings_dict["attention_mask"]

In [179]:
eos_not_in_sents = torch.ones(input_ids.shape[0]).long()

In [180]:
attn_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [181]:
eos_not_in_sents

tensor([1, 1, 1])

In [182]:
last_non_masked_idx = torch.sum(attn_mask, dim=1) - 1

In [183]:
last_non_masked_idx

tensor([11, 10, 26])

In [184]:
start_idx = inp_idx = (last_non_masked_idx).view(-1, 1).repeat(1, 800).unsqueeze(1)

In [185]:
start_idx

tensor([[[11, 11, 11,  ..., 11, 11, 11]],

        [[10, 10, 10,  ..., 10, 10, 10]],

        [[26, 26, 26,  ..., 26, 26, 26]]])

In [186]:
start_idx.shape

torch.Size([3, 1, 800])

In [187]:
position_ids = torch.tensor([list(range(40)) for i in range(input_ids.shape[0])])

In [188]:
position_ids

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39]])

In [189]:
for i, position_ids_slice in enumerate(position_ids):
    position_ids_slice[last_non_masked_idx[i]:] = position_ids_slice[last_non_masked_idx[i]]

In [190]:
position_ids_slice

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26])

In [191]:
src_tokens = torch.tensor([[2,1,1],[3,1,0]])

In [192]:
device = src_tokens.device

In [193]:
device

device(type='cpu')

In [194]:
eos_id = 5

In [195]:
cat_tensor = torch.tensor([eos_id]).view(-1,1)

In [198]:
cat_tensor

tensor([[5]])

In [200]:
e = cat_tensor.expand(2,-1)

In [203]:
e.shape

torch.Size([2, 1])

In [204]:
src_tokens.shape

torch.Size([2, 3])

In [209]:
e

tensor([[5],
        [5]])

In [210]:
src_tokens

tensor([[2, 1, 1],
        [3, 1, 0]])

In [212]:
a = src_tokens.size(0)
a

2

In [207]:
res = torch.cat((e, src_tokens[:,1:]),1)

In [208]:
res

tensor([[5, 1, 1],
        [5, 1, 0]])

In [221]:
a = torch.ones([2,2,3])
b = torch.ones([2,2,3])*2
c = torch.ones([2,2,3])*6

In [222]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [223]:
b

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [224]:
c  

tensor([[[6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.]]])

In [227]:
res = torch.mean(torch.stack([a,b,c]),0)

In [228]:
res

tensor([[[3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.]]])

In [229]:
res.shape

torch.Size([2, 2, 3])

In [230]:
z = torch.stack([a,b,c])

In [231]:
z

tensor([[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]],


        [[[6., 6., 6.],
          [6., 6., 6.]],

         [[6., 6., 6.],
          [6., 6., 6.]]]])

In [232]:
z.shape

torch.Size([3, 2, 2, 3])

In [233]:
from difflib import SequenceMatcher

In [234]:
src = [22138, 82, 64, 2254, 164, 7, 5, 11605, 11,5]

In [235]:
trg = [22138, 82, 64, 2254, 164,8,7,4,11605,22,5]

In [236]:
matcher = SequenceMatcher(None, src, trg)

In [238]:
diffs = list(matcher.get_opcodes())

In [239]:
for diff in diffs:
    tag, i1,i2,j1,j2 = diff
    print(diff)

('equal', 0, 5, 0, 5)
('insert', 5, 5, 5, 6)
('equal', 5, 6, 6, 7)
('insert', 6, 6, 7, 10)
('equal', 6, 7, 10, 11)
('delete', 7, 10, 11, 11)


In [240]:
a = torch.randn(2,3,8)
b = torch.randn(2,3,8)
c = torch.randn(2,3,8)

In [241]:
a.shape

torch.Size([2, 3, 8])

In [242]:
res = torch.cat((a,b,c),dim=-1)

In [243]:
res.shape

torch.Size([2, 3, 24])

In [245]:
embed = torch.nn.Embedding(40, 200)

In [246]:
embed

Embedding(40, 200)

In [247]:
embed.shape

AttributeError: 'Embedding' object has no attribute 'shape'

In [248]:
re = torch.nn.ReLU(inplace=True)

In [249]:
import pandas as pd

In [263]:
dtype = {'timestamp': 'int64', 
         'user_id': 'int64' ,
         'content_id': 'int16',
         'content_type_id': 'int8',
         'answered_correctly':'int8',
         'prior_question_elapsed_time':'float64'}

train_df = pd.read_csv('/Users/hesu/Documents/KT/riiid/train_1M.csv', usecols=[1,2,3,4,7,8], dtype=dtype)
train_df.head()

timestamp  user_id  content_id  content_type_id  answered_correctly  \
0          0      115        5692                0                   1   
1      56943      115        5716                0                   1   
2     118363      115         128                0                   1   
3     131167      115        7860                0                   1   
4     137965      115        7922                0                   1   

   prior_question_elapsed_time  
0                          NaN  
1                      37000.0  
2                      55000.0  
3                      19000.0  
4                      11000.0

In [264]:
elapsed_mean = train_df.prior_question_elapsed_time.mean()
elapsed_mean

25302.941492979444

In [265]:
train_df['prior_question_elapsed_time'].fillna(elapsed_mean, inplace=True)


In [ ]:
# load question dataframe
questions = pd.read_csv('/kaggle/input/riiid-test-answer-prediction/questions.csv')
# fix one row with an empty tag list which gets interpreted as float
inv_rows = questions[questions['tags'].apply(type) == float].index
questions.at[inv_rows, 'tags'] = ''
# split tag string into list of ints
questions['tags'] = questions['tags'].apply(lambda x: np.array(x.split()).astype(int))

In [253]:
questions = pd.read_csv('/Users/hesu/Documents/KT/riiid/questions.csv')

In [254]:
inv_rows = questions[questions['tags'].apply(type) == float].index
# 找到tags为空的question

In [255]:
inv_rows

Int64Index([10033], dtype='int64')

In [256]:
questions.at[inv_rows, 'tags'] = ''


In [257]:
questions.iloc[10033]

question_id       10033
bundle_id         10033
correct_answer        2
part                  6
tags                   
Name: 10033, dtype: object

In [258]:
questions.head(10)

question_id  bundle_id  correct_answer  part            tags
0            0          0               0     1   51 131 162 38
1            1          1               1     1       131 36 81
2            2          2               0     1  131 101 162 92
3            3          3               0     1  131 149 162 29
4            4          4               3     1    131 5 162 38
5            5          5               2     1  131 149 162 81
6            6          6               2     1    10 94 162 92
7            7          7               0     1   61 110 162 29
8            8          8               3     1   131 13 162 92
9            9          9               3     1       10 164 81

In [259]:
questions['tags'] = questions['tags'].apply(lambda x: np.array(x.split()).astype(int))
# 将tag的数据取出来

In [260]:
questions.head(10)

question_id  bundle_id  correct_answer  part                 tags
0            0          0               0     1   [51, 131, 162, 38]
1            1          1               1     1        [131, 36, 81]
2            2          2               0     1  [131, 101, 162, 92]
3            3          3               0     1  [131, 149, 162, 29]
4            4          4               3     1    [131, 5, 162, 38]
5            5          5               2     1  [131, 149, 162, 81]
6            6          6               2     1    [10, 94, 162, 92]
7            7          7               0     1   [61, 110, 162, 29]
8            8          8               3     1   [131, 13, 162, 92]
9            9          9               3     1        [10, 164, 81]

In [261]:
all_tags = np.unique(np.concatenate(questions['tags'].values))
# 取出所有的tag的类型

In [262]:
all_tags

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [266]:
train_df = pd.merge(train_df, questions, left_on='content_id',right_on='question_id',how='left')


In [267]:
train_df.head(10)

timestamp  user_id  content_id  content_type_id  answered_correctly  \
0          0      115        5692                0                   1   
1      56943      115        5716                0                   1   
2     118363      115         128                0                   1   
3     131167      115        7860                0                   1   
4     137965      115        7922                0                   1   
5     157063      115         156                0                   1   
6     176092      115          51                0                   1   
7     194190      115          50                0                   1   
8     212463      115        7896                0                   1   
9     230983      115        7863                0                   1   

   prior_question_elapsed_time  question_id  bundle_id  correct_answer  part  \
0                 25302.941493       5692.0     5692.0             3.0   5.0   
1                 37000.000000       5716.0     5716.0             2.0   5.0   
2                 55000.000000        128.0      128.0             0.0   1.0   
3                 19000.000000       7860.0     7860.0             0.0   1.0   
4                 11000.000000       7922.0     7922.0             1.0   1.0   
5                  5000.000000        156.0      156.0             2.0   1.0   
6                 17000.000000         51.0       51.0             0.0   1.0   
7                 17000.000000         50.0       50.0             3.0   1.0   
8                 16000.000000       7896.0     7896.0             2.0   1.0   
9                 16000.000000       7863.0     7863.0             0.0   1.0   

                  tags  
0                [151]  
1                [168]  
2       [131, 149, 92]  
3       [131, 104, 81]  
4       [131, 149, 92]  
5  [131, 101, 162, 38]  
6       [131, 187, 81]  
7       [131, 101, 38]  
8  [131, 104, 162, 81]  
9        [131, 68, 92]

In [268]:
group = train_df[['user_id', 'content_id', 'answered_correctly']].groupby('user_id').apply(lambda r: (
            r['content_id'].values,
            r['answered_correctly'].values))


In [269]:
len(group)

3824

In [271]:
group.iloc[0]

(array([5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,
         104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,
          45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,
        7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2064, 2063, 3363,
        3365, 3364], dtype=int16),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1], dtype=int8))

In [272]:
group_tags = train_df[['user_id', 'content_id', 'answered_correctly','tags']].groupby('user_id').apply(lambda r: (
            r['content_id'].values,
            r['answered_correctly'].values,
            r['tags'].values))


In [273]:
group_tags.iloc[0]

(array([5692, 5716,  128, 7860, 7922,  156,   51,   50, 7896, 7863,  152,
         104,  108, 7900, 7901, 7971,   25,  183, 7926, 7927,    4, 7984,
          45,  185,   55, 7876,    6,  172, 7898,  175,  100, 7859,   57,
        7948,  151,  167, 7897, 7882, 7962, 1278, 2065, 2064, 2063, 3363,
        3365, 3364], dtype=int16),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1], dtype=int8),
 array([array([151]), array([168]), array([131, 149,  92]),
        array([131, 104,  81]), array([131, 149,  92]),
        array([131, 101, 162,  38]), array([131, 187,  81]),
        array([131, 101,  38]), array([131, 104, 162,  81]),
        array([131,  68,  92]), array([131,   5, 162,  81]),
        array([131,  93, 162,  81]), array([131, 104,  92]),
        array([131,  93,  81]), array([131, 130,  92]),
        array([131,  93,  92]), array([ 9, 10, 81]),
        array([ 61, 110,

In [274]:
tags1 = group_tags.iloc[0][2]

In [275]:
tags1

array([array([151]), array([168]), array([131, 149,  92]),
       array([131, 104,  81]), array([131, 149,  92]),
       array([131, 101, 162,  38]), array([131, 187,  81]),
       array([131, 101,  38]), array([131, 104, 162,  81]),
       array([131,  68,  92]), array([131,   5, 162,  81]),
       array([131,  93, 162,  81]), array([131, 104,  92]),
       array([131,  93,  81]), array([131, 130,  92]),
       array([131,  93,  92]), array([ 9, 10, 81]),
       array([ 61, 110, 162,  29]), array([ 9, 10, 92]),
       array([ 10, 178,  29]), array([131,   5, 162,  38]),
       array([131, 104,  81]), array([ 10, 164, 162,  81]),
       array([131, 111,  81]), array([131,  36, 162,  81]),
       array([10, 94, 92]), array([ 10,  94, 162,  92]),
       array([ 10, 164,  81]), array([131,  99,  29]),
       array([ 9, 10, 92]), array([131,   5,  81]),
       array([131,   5,  92]), array([131,  93, 162,  29]),
       array([131, 187,  29]), array([131,  93, 162,  92]),
       array([131,

In [276]:
len(tags1)

46

In [277]:
c = tags1[0]

In [278]:
c

array([151])

In [279]:
type(tags1)

numpy.ndarray

In [280]:
d2 = np.ones([80,1])

In [281]:
d2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [283]:
length = len(tags1)
length

46

In [284]:
d2[-length:] = tags1

ValueError: could not broadcast input array from shape (46) into shape (46,1)

In [285]:
d2.shape

(80, 1)

In [286]:
tags1.shape

(46,)

In [287]:
d1 = np.ones(80)

In [288]:
d1.shape

(80,)

In [289]:
d1[-length:] = tags1

ValueError: setting an array element with a sequence.

In [290]:
type(d1)

numpy.ndarray

In [291]:
type(tags1)

numpy.ndarray

In [ ]:
class ValidDataset(Dataset):
    def __init__(self, samples, test_df, n_skill,n_ela_skill, max_seq=MAX_SEQ): #HDKIM 100
        super(ValidDataset, self).__init__()
        self.samples = samples
        self.user_ids = [x for x in test_df["user_id"].unique()]
        self.test_df = test_df
        self.n_ela_skill = n_ela_skill
        self.n_skill = n_skill
        self.max_seq = max_seq

    def __len__(self):
        return self.test_df.shape[0]

    def __getitem__(self, index):
        test_info = self.test_df.iloc[index]

        user_id = test_info["user_id"]
        target_id = test_info["content_id"]
        ela_target_id = test_info["prior_question_elapsed_time"]
        part_target_id = test_info["part"]
        com_target_id = test_info["community"]

        
        label = test_info['answered_correctly']

        q = np.ones(self.max_seq, dtype=int)*13523
        qa = np.zeros(self.max_seq, dtype=int)
        ela = np.ones(self.max_seq, dtype=int)*301
        part = np.ones(self.max_seq, dtype=int)*7
        com = np.ones(self.max_seq, dtype=int)*4

        if user_id in self.samples.index:
            q_, qa_, ela_, part_,com_ = self.samples[user_id]
            
            seq_len = len(q_)

            if seq_len >= self.max_seq:
                q = q_[-self.max_seq:]
                qa = qa_[-self.max_seq:]
                ela = ela_[-self.max_seq:]
                part = part_[-self.max_seq:]
                com = com_[-self.max_seq:]
                
            else:
                q[-seq_len:] = q_
                qa[-seq_len:] = qa_       
                ela[-seq_len:] = ela_
                part[-seq_len:] = part_
                com[-seq_len:] = com_
        
        x = np.ones(self.max_seq-1, dtype=int)*13523
        x = q[1:].copy()
#         x += (qa[1:] == 1) * self.n_skill
        
        questions = np.append(q[2:], [target_id])
        
        ela_x = np.ones(self.max_seq-1, dtype=int)*301
        ela_x = ela[1:].copy()
#         ela_x += (qa[1:] == 1) * self.n_ela_skill
        
        ela_target = np.append(ela[2:],[ela_target_id])
        
        part_x = np.ones(self.max_seq-1, dtype=int)*7
        part_x = part[1:].copy()
        
        part_target = np.append(part[2:],[part_target_id])

        com_x = np.ones(self.max_seq-1, dtype=int)*4
        com_x = com[1:].copy()
        
        com_target = np.append(com[2:],[com_target_id])
        
        ans_x = np.zeros(self.max_seq-1, dtype=int)
        ans_x = qa[1:].copy()
#         return x, questions, ela_x, ela_target, np.array([label])
        return torch.LongTensor(x), torch.LongTensor(questions),\
            torch.LongTensor(ela_x), torch.LongTensor(ela_target),\
            torch.LongTensor(part_x), torch.LongTensor(part_target),\
            torch.LongTensor(com_x), torch.LongTensor(com_target),\
            torch.LongTensor(ans_x),\
            torch.FloatTensor(np.array([label]))