In [5]:
import torch
from torch import nn 
from torch import optim

In [9]:
model = nn.Linear(20, 5) # predict logits for 5 classes
x = torch.randn(1, 20)
y = torch.tensor([[1., 0., 1., 0., 0.]]) # get classA and classC as active

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(model.parameters(), lr=1e-1)

for epoch in range(20):
    optimizer.zero_grad()
    output = model(x)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
    print('Loss: {:.3f}'.format(loss.item()))

Loss: 0.660
Loss: 0.577
Loss: 0.509
Loss: 0.452
Loss: 0.404
Loss: 0.364
Loss: 0.331
Loss: 0.302
Loss: 0.277
Loss: 0.256
Loss: 0.238
Loss: 0.221
Loss: 0.207
Loss: 0.194
Loss: 0.183
Loss: 0.173
Loss: 0.164
Loss: 0.155
Loss: 0.148
Loss: 0.141


In [14]:
model = nn.Linear(20, 5) # predict logits for 5 classes
x = torch.randn(1,3,20)
y = torch.tensor([[[1., 0., 1., 0., 0.],[1.,1.,0.,0.,1.],[0.,1.,0.,1.,0.]]]) # get classA and classC as active

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(model.parameters(), lr=1e-1)

for epoch in range(20):
    optimizer.zero_grad()
    output = model(x)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
    print('Loss: {:.3f}'.format(loss.item()))

Loss: 0.868
Loss: 0.825
Loss: 0.786
Loss: 0.748
Loss: 0.713
Loss: 0.680
Loss: 0.650
Loss: 0.621
Loss: 0.594
Loss: 0.569
Loss: 0.545
Loss: 0.523
Loss: 0.503
Loss: 0.484
Loss: 0.466
Loss: 0.449
Loss: 0.433
Loss: 0.418
Loss: 0.404
Loss: 0.391


In [44]:
x = torch.rand(1,3,5)

In [55]:
x

tensor([[[0.6447, 0.9727, 0.8581, 0.0756, 0.4917],
         [0.1604, 0.2060, 0.8445, 0.3627, 0.2917],
         [0.6351, 0.2305, 0.0730, 0.4323, 0.2172]]])

In [39]:
bce = nn.BCEWithLogitsLoss()

In [40]:
loss = 0

In [46]:
y = torch.tensor([[[1., 0., 1., 0., 0.],[1.,1.,0.,0.,1.],[0.,1.,0.,1.,0.]]])

In [47]:
x.size(0)

1

In [48]:
attention_mask = torch.tensor([[1,1,1,1,1],[1,1,1,1,0]])


In [49]:
attention_mask

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0]])

In [53]:
length = torch.sum(attention_mask, dim=1)
length

tensor([5, 4])

In [54]:
def sequence_multi_label_loss(logits, tagrets, length):
    bce = nn.BCEWithLogitsLoss()
    loss = 0
    for batch_num in range(logits.size(0)):
        for i in range(logits.size(1)):
            if i < length[batch_num]:
                loss += bce(logits[batch_num][i], tagrets[batch_num][i])
    loss = loss / length.float().sum()
    return loss

In [56]:
loss_func = nn.BCEWithLogitsLoss()
loss1 = loss_func(x,y)

In [57]:
loss1

tensor(0.7543)

In [58]:
length = torch.tensor([3])

In [59]:
length

tensor([3])

In [60]:
loss2 = sequence_multi_label_loss(x,y,length)
loss2

tensor(0.7543)

In [64]:
y = torch.tensor([[[1., 0., 1., 0., 0.],[1.,1.,0.,0.,1.],[0.,1.,0.,1.,0.]]],dtype=torch.float)

In [65]:
y

tensor([[[1., 0., 1., 0., 0.],
         [1., 1., 0., 0., 1.],
         [0., 1., 0., 1., 0.]]])

In [66]:
loss2 = sequence_multi_label_loss(x,y,length)
loss2

tensor(0.7543)

In [67]:
a = torch.FloatTensor([1,2])

In [68]:
a

tensor([1., 2.])

In [69]:
b = torch.zeros(2,dtype=torch.float)

In [70]:
b

tensor([0., 0.])