In [3]:
#测试torch.bmm()如何实现三维矩阵乘法的
#测试结果发现，三维矩阵相乘还是通过底部的二维矩阵先相乘，然后不断往前面的高维堆砌前进


import torch

q = torch.ones(24).view(2,3,4)
print(q)
k = torch.ones(24).view(2,3,4)
k = k.transpose(1,2)
print(k)
attention = torch.bmm(q, k)
print(attention.size())
print(attention)

#我们用两个三维矩阵，维度分别为(2,3,4),(2,4,3)，进行矩阵的乘法，
#最后得到的attention的维度为(2,3,3),
#我的理解也就是说其实是(3,4)和(4,3)矩阵进行相乘，为了验证结果，我们设置新的两个三维矩阵，看他们相乘的结果是什么


a = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
print(a.size())


b = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
b = b.transpose(1,2)

attention2 = torch.bmm(a,b)
print("attention2.size is:", attention2.size())
print("attention2 is:", attention2)
#attention2的结果也验证了我们的想法。三维矩阵，其实还是二维矩阵的乘法实现的，
#用最后两个维度的矩阵实现乘法，然后不断的堆砌往前面的维度前进


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])
torch.Size([2, 3, 4])
attention2.size is: torch.Size([2, 3, 3])
attention2 is: tensor([[[ 4,  4,  4],
         [ 4,  4,  4],
         [ 4,  4,  4]],

        [[16, 16, 16],
         [16, 16, 16],
         [16, 16, 16]]])


In [1]:
#测试dropout的功能
#实验的结果显示，dropout层是按照一定的概率将某些值置为0，目前还没有看dropout的具体源码

import torch
import torch.nn as nn

#a = torch.arange(24).view(2,3,4)
a = torch.ones((2,3,4))
print(a)

dropout_layer = nn.Dropout(0.1)
b = dropout_layer(a)
print(b)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1.1111, 1.1111, 1.1111, 1.1111],
         [0.0000, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 1.1111]],

        [[1.1111, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 0.0000],
         [1.1111, 1.1111, 1.1111, 1.1111]]])


In [1]:
label_ids = [1,2,3,4]
d_tags_ids = [1,1,1,1]
input_ids = [1,2,3,4]
pred_mask = [1,1,1,1]


In [3]:
label_id = 5
token_id = [2,4,5]
d_tag_id = 1


In [4]:
label_ids.extend([label_id]*len(token_id))
input_ids.extend(token_id)
d_tags_ids.extend([d_tag_id]*len(token_id))
pred_mask.extend([1]+[0]*(len(token_id)-1))

In [5]:
label_ids


[1, 2, 3, 4, 5, 5, 5]

In [6]:
d_tags_ids

[1, 1, 1, 1, 1, 1, 1]

In [7]:
input_ids

[1, 2, 3, 4, 2, 4, 5]

In [8]:
pred_mask

[1, 1, 1, 1, 1, 0, 0]

In [9]:
import transformers

I1028 16:14:07.937288 4445881792 file_utils.py:40] PyTorch version 1.4.0 available.


In [10]:
from transformers import BertTokenizer, BertConfig

In [19]:
tokenizer = BertTokenizer.from_pretrained("../../../AiQuestion/gector/model/bert-base-cased/")

I1028 16:16:43.492889 4445881792 tokenization_utils.py:327] Model name '../../../AiQuestion/gector/model/bert-base-cased/' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). Assuming '../../../AiQuestion/gector/model/bert-base-cased/' is a path or url to a directory containing tokenizer files.
I1028 16:16:43.494362 4445881792 tokenization_utils.py:359] Didn't find file ../../../AiQuestion/gector/model/bert-base-cased/added_tokens.json. We won't load it.
I1028 16:16:43.494868 4445881792 tokenization_utils.py:359] Didn't find file ../../../AiQuestion

In [13]:
import torch

In [14]:
 ids = torch.tensor([101,1184,1110,7434,3187,136,102])


In [15]:
 tokens = tokenizer.convert_ids_to_tokens(ids)

In [16]:
tokens

['[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]']

In [18]:
!pwd

/Users/hesu/Documents/notes/jupyter/pytorch


In [20]:
 ids = torch.tensor([101,1184,1110,7434,3187,136,102])


In [21]:
ids

tensor([ 101, 1184, 1110, 7434, 3187,  136,  102])

In [1]:
input_ids = torch.tensor([101,25527,117,1126,2728,8734,2093,1103])
res = tokenizer.convert_ids_to_tokens(input_ids)


NameError: name 'torch' is not defined

In [3]:
import numpy as mp
import sys

if "../" not in sys.path:
  sys.path.append("../") 

In [4]:
from lib.envs.gridworld import GridworldEnv

ModuleNotFoundError: No module named 'lib'

In [3]:
def getNext(w):
    # 构建next数组的核心思想就是，求当前位置的后缀和起始点的前缀的最大的公共子序列的长度
#     http://www.ruanyifeng.com/blog/2013/05/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm.html
    array = [0]*len(w)
    
    i = 1
    m = 0
    
    while i < len(w):
        print("i is:{}\t m is:{}\t array is:{}".format(i,m,array))

        if w[i] == w[m]:
            # 当前位置i的值和前缀位置相等，那么可以给m+1，因为m初始值为0，然后赋值给array[i]
            # 同理当后续i+1和m+1的位置相等时，可以不断的迭代下去
            m += 1
            array[i] = m
            i += 1
        elif w[i] != w[m] and m != 0:
            # 这里是当i和m位置的值，不相等，并且m不等于；
            # 这种情况就是比如字符串"ACABACACD"走到i=7时，此时m=3，因为第4个字符到第6个字符"ACA"和第0个字符到底2个字符"ACA"相等，
            # 但是此时第7个字符"C"和第3个字符"B"不相等，那么我们此时要如何操作呢？
            # 此时，我们要铭记我们的nexrt数组的主旨是要存储当前位置i的后缀和起始位置0的最长匹配串。
            #【我们此时之所以匹配第i个字符和第m个字符是否相等，是因为我们已经知道第0到第m-1个字符和从第i-m-1到第i-1个字符相等】
            # 既然从0到m位置的匹配无法成功，那么我们就需要缩短匹配的字符串长度，此时我们其实是知道第i-1个字符串和第m-1个字符是相等的，
            # 那么我们其实可以找到第m-1个字符串的最长匹配长度，在他的基础上再来匹配最长长度。
            # 也就是我们其实根据next数组array还知道一个信息，就是从第0个字符到第array[m-1]-1个字符
            # 其实和从第i-array[m-1]个字符到第i-1个字符是相等的【这个信息其实是根据array[m-1]的值得到的】；
            # 所以我们接下来需要判断第i个字符和第array[m-1]个字符是否相等
            # 所以这里其实也可以写成循环的方式
            # 注意这里对i没有执行+1操作
            m = array[m-1]
        else:
            array[i] = 0
            i += 1
            
        
        
    return array


In [4]:
res = getNext("ACABACACD")

i is:1	 m is:0	 array is:[0, 0, 0, 0, 0, 0, 0, 0, 0]
i is:2	 m is:0	 array is:[0, 0, 0, 0, 0, 0, 0, 0, 0]
i is:3	 m is:1	 array is:[0, 0, 1, 0, 0, 0, 0, 0, 0]
i is:3	 m is:0	 array is:[0, 0, 1, 0, 0, 0, 0, 0, 0]
i is:4	 m is:0	 array is:[0, 0, 1, 0, 0, 0, 0, 0, 0]
i is:5	 m is:1	 array is:[0, 0, 1, 0, 1, 0, 0, 0, 0]
i is:6	 m is:2	 array is:[0, 0, 1, 0, 1, 2, 0, 0, 0]
i is:7	 m is:3	 array is:[0, 0, 1, 0, 1, 2, 3, 0, 0]
i is:7	 m is:1	 array is:[0, 0, 1, 0, 1, 2, 3, 0, 0]
i is:8	 m is:2	 array is:[0, 0, 1, 0, 1, 2, 3, 2, 0]
i is:8	 m is:0	 array is:[0, 0, 1, 0, 1, 2, 3, 2, 0]


In [5]:
def getNext(w):
    array = [0]*len(w)
    
    i = 1
    m = 0
    while i < len(w):
        if w[i] == w[m]:
            m += 1
            array[i] = m
            i += 1
        elif w[i] != w[m] and m != 0:
            while w[i] != w[m] and m != 0:
                m = array[m-1]
        else:
            array[i] = 0
            i += 1
    return array
    
    

In [6]:
res = getNext("ACABACACD")
res

[0, 0, 1, 0, 1, 2, 3, 2, 0]

In [7]:
a = "abcdeffg"

In [8]:
c = a[2:5]

In [9]:
c

'cde'

In [10]:
a[2] = 'g'

TypeError: 'str' object does not support item assignment

In [ ]:
class Solution:
    def nextPermutation(self, nums):
        """
        :type nums: List[int]
        :rtype: void Do not return anything, modify nums in-place instead.
        """
        i = j = r = len(nums) - 1
        while i > 0 and nums[i] <= nums[i-1]:
            i -= 1
            
        i -= 1
        if i >= 0:
            while j >= i and nums[j] <= nums[i]:
                j -= 1

            nums[i], nums[j] = nums[j], nums[i]
        
        i += 1
        while i < r:
            nums[i], nums[r] = nums[r], nums[i]
            i += 1
            r -= 1
