In [3]:
#测试torch.bmm()如何实现三维矩阵乘法的
#测试结果发现，三维矩阵相乘还是通过底部的二维矩阵先相乘，然后不断往前面的高维堆砌前进


import torch

q = torch.ones(24).view(2,3,4)
print(q)
k = torch.ones(24).view(2,3,4)
k = k.transpose(1,2)
print(k)
attention = torch.bmm(q, k)
print(attention.size())
print(attention)

#我们用两个三维矩阵，维度分别为(2,3,4),(2,4,3)，进行矩阵的乘法，
#最后得到的attention的维度为(2,3,3),
#我的理解也就是说其实是(3,4)和(4,3)矩阵进行相乘，为了验证结果，我们设置新的两个三维矩阵，看他们相乘的结果是什么


a = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
print(a.size())


b = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
b = b.transpose(1,2)

attention2 = torch.bmm(a,b)
print("attention2.size is:", attention2.size())
print("attention2 is:", attention2)
#attention2的结果也验证了我们的想法。三维矩阵，其实还是二维矩阵的乘法实现的，
#用最后两个维度的矩阵实现乘法，然后不断的堆砌往前面的维度前进


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])
torch.Size([2, 3, 4])
attention2.size is: torch.Size([2, 3, 3])
attention2 is: tensor([[[ 4,  4,  4],
         [ 4,  4,  4],
         [ 4,  4,  4]],

        [[16, 16, 16],
         [16, 16, 16],
         [16, 16, 16]]])


In [1]:
#测试dropout的功能
#实验的结果显示，dropout层是按照一定的概率将某些值置为0，目前还没有看dropout的具体源码

import torch
import torch.nn as nn

#a = torch.arange(24).view(2,3,4)
a = torch.ones((2,3,4))
print(a)

dropout_layer = nn.Dropout(0.1)
b = dropout_layer(a)
print(b)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1.1111, 1.1111, 1.1111, 1.1111],
         [0.0000, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 1.1111]],

        [[1.1111, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 0.0000],
         [1.1111, 1.1111, 1.1111, 1.1111]]])


In [1]:
label_ids = [1,2,3,4]
d_tags_ids = [1,1,1,1]
input_ids = [1,2,3,4]
pred_mask = [1,1,1,1]


In [3]:
label_id = 5
token_id = [2,4,5]
d_tag_id = 1


In [4]:
label_ids.extend([label_id]*len(token_id))
input_ids.extend(token_id)
d_tags_ids.extend([d_tag_id]*len(token_id))
pred_mask.extend([1]+[0]*(len(token_id)-1))

In [5]:
label_ids


[1, 2, 3, 4, 5, 5, 5]

In [6]:
d_tags_ids

[1, 1, 1, 1, 1, 1, 1]

In [7]:
input_ids

[1, 2, 3, 4, 2, 4, 5]

In [8]:
pred_mask

[1, 1, 1, 1, 1, 0, 0]

In [9]:
import transformers

I1028 16:14:07.937288 4445881792 file_utils.py:40] PyTorch version 1.4.0 available.


In [10]:
from transformers import BertTokenizer, BertConfig

In [19]:
tokenizer = BertTokenizer.from_pretrained("../../../AiQuestion/gector/model/bert-base-cased/")

I1028 16:16:43.492889 4445881792 tokenization_utils.py:327] Model name '../../../AiQuestion/gector/model/bert-base-cased/' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). Assuming '../../../AiQuestion/gector/model/bert-base-cased/' is a path or url to a directory containing tokenizer files.
I1028 16:16:43.494362 4445881792 tokenization_utils.py:359] Didn't find file ../../../AiQuestion/gector/model/bert-base-cased/added_tokens.json. We won't load it.
I1028 16:16:43.494868 4445881792 tokenization_utils.py:359] Didn't find file ../../../AiQuestion

In [13]:
import torch

In [14]:
 ids = torch.tensor([101,1184,1110,7434,3187,136,102])


In [15]:
 tokens = tokenizer.convert_ids_to_tokens(ids)

In [16]:
tokens

['[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]']

In [18]:
!pwd

/Users/hesu/Documents/notes/jupyter/pytorch


In [20]:
 ids = torch.tensor([101,1184,1110,7434,3187,136,102])


In [21]:
ids

tensor([ 101, 1184, 1110, 7434, 3187,  136,  102])

In [ ]:
input_ids = torch.tensor([101,25527,117,1126,2728,8734,2093,1103])
res = tokenizer.convert_ids_to_tokens(input_ids)
