In [3]:
#测试torch.bmm()如何实现三维矩阵乘法的
#测试结果发现，三维矩阵相乘还是通过底部的二维矩阵先相乘，然后不断往前面的高维堆砌前进


import torch

q = torch.ones(24).view(2,3,4)
print(q)
k = torch.ones(24).view(2,3,4)
k = k.transpose(1,2)
print(k)
attention = torch.bmm(q, k)
print(attention.size())
print(attention)

#我们用两个三维矩阵，维度分别为(2,3,4),(2,4,3)，进行矩阵的乘法，
#最后得到的attention的维度为(2,3,3),
#我的理解也就是说其实是(3,4)和(4,3)矩阵进行相乘，为了验证结果，我们设置新的两个三维矩阵，看他们相乘的结果是什么


a = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
print(a.size())


b = torch.tensor([[[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]],
                  [[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]]])
b = b.transpose(1,2)

attention2 = torch.bmm(a,b)
print("attention2.size is:", attention2.size())
print("attention2 is:", attention2)
#attention2的结果也验证了我们的想法。三维矩阵，其实还是二维矩阵的乘法实现的，
#用最后两个维度的矩阵实现乘法，然后不断的堆砌往前面的维度前进


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])
torch.Size([2, 3, 4])
attention2.size is: torch.Size([2, 3, 3])
attention2 is: tensor([[[ 4,  4,  4],
         [ 4,  4,  4],
         [ 4,  4,  4]],

        [[16, 16, 16],
         [16, 16, 16],
         [16, 16, 16]]])


In [1]:
#测试dropout的功能
#实验的结果显示，dropout层是按照一定的概率将某些值置为0，目前还没有看dropout的具体源码

import torch
import torch.nn as nn

#a = torch.arange(24).view(2,3,4)
a = torch.ones((2,3,4))
print(a)

dropout_layer = nn.Dropout(0.1)
b = dropout_layer(a)
print(b)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1.1111, 1.1111, 1.1111, 1.1111],
         [0.0000, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 1.1111]],

        [[1.1111, 1.1111, 1.1111, 1.1111],
         [1.1111, 1.1111, 1.1111, 0.0000],
         [1.1111, 1.1111, 1.1111, 1.1111]]])
