# NLLLoss

In [19]:
import torch

input = torch.randn(3,3)
print(input)




tensor([[ 0.2535, -0.1052, -1.6368],
        [-0.7883,  0.2348,  1.2417],
        [ 0.5463,  0.5246,  1.2829]])


In [20]:
import torch.nn as nn

sm = nn.Softmax(dim=1)
sm(input)

tensor([[0.5407, 0.3777, 0.0817],
        [0.0877, 0.2441, 0.6682],
        [0.2459, 0.2406, 0.5136]])

In [21]:
log = torch.log(sm(input))
print(log)



tensor([[-0.6150, -0.9737, -2.5053],
        [-2.4333, -1.4102, -0.4032],
        [-1.4030, -1.4247, -0.6664]])


In [22]:
#(1.0769+1.4630+0.6830)/3
#(0.4155+1.0945+1.5285)/3
(0.6150+0.4032+1.4247)/3

0.8142999999999999

In [25]:
#下面我们调用pytorch的NLLLoss函数来验证一下；
loss = nn.NLLLoss()
target = torch.tensor([0,2,1])
print(loss(log, target))




tensor(0.8143)


# CrossEntropy

In [26]:
loss=nn.CrossEntropyLoss()

print(loss(input, target))

tensor(0.8143)
