In [1]:
#pytorch是一个基于python的科学计算包，主要定位两种人群
#1、numpy的替代品，可以利用GPU的性能进行计算。
#2、深度学习研究平台拥有足够的灵活性和速度





In [2]:
#张量Tensor
#Tensor类似于numpy中的ndarrays,同时tensors可以使用GPU进行计算
import torch

x = torch.empty(5,3)
#torch.empty()可以不初始化的构建矩阵
print(x)

x = torch.rand(5,3)
#torch.rand()可以随机初始化一个矩阵
print(x)

x = torch.zeros(5,3, dtype=torch.long)
#torch.zeros()可以构建一个全是0的矩阵
print(x)

x = torch.tensor([5.5,3])
#torch.tensor()可以直接使用数据构建一个张量
print(x)

x = torch.ones(5,3)
#torch.ones()可以创建全是1的矩阵
print(x)

y = x.new_ones(5,3)
#tensor.new_ones()可以继承原tensor的数据类型dataType，来生成新的tensor
#tensor.ones()是直接生成新的tensor
print(y)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  1.4569e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28],
        [ 1.4603e-19,  1.0899e+27,  6.8943e+34],
        [ 1.1835e+22,  7.0976e+22,  1.8515e+28]])
tensor([[0.4467, 0.8242, 0.6860],
        [0.7444, 0.7867, 0.0798],
        [0.4781, 0.0286, 0.8030],
        [0.3589, 0.8433, 0.4196],
        [0.9569, 0.0645, 0.8398]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.8580,  0.6247,  0.0648],
        [ 0.1715, -1.2764,  1.0940],
        [-0.4517,  0.9479,  1.7505],
        [ 0.1424,  0.2202, -0.7999],
        [-1.9016, -1.1691, -0.5384]])


In [4]:
#torch.rand()和torch.randn()的区别是什么
#一个是均匀分布，一个是正态分布

#torch.rand(*sizes, out=None)返回一个张量，包含了从区间[0,1)的均匀分布中抽取的一组随机数，张量的形状由参数sizes定义

#torch.randn(*sizes, out=None)返回一个张量，包含了从正态分布(均值为0，方差为1，即高斯分布)中抽取的一组随机数，张量的形状由sizes决定


x = torch.randn(5,3)
print(x)

y = torch.rand(5,3)
print(y)

tensor([[-0.3437, -0.1685, -1.1374],
        [ 0.2528, -0.2483,  0.8504],
        [-1.3674,  1.8896, -0.2811],
        [-0.5810,  0.0848,  0.0230],
        [ 2.1306,  0.9101, -0.6635]])
tensor([[0.4810, 0.8788, 0.9358],
        [0.2410, 0.8808, 0.6105],
        [0.7998, 0.7386, 0.2780],
        [0.1035, 0.8543, 0.7332],
        [0.8008, 0.8949, 0.3246]])


In [ ]:
#Tensor attributes
#在tensor attributes中有三个类，分别为torch.dtype、torch.device和torch.layout。
#其中torch.dtype是展示torch.Tensor数据类型的类，pytorch有八个不同的数据类型，下表是完整的dtype列表
#1: 32-bit floating point -> torch.float32 or torch.float
#2: 64-bit floating point -> torch.float64 or torch.double
#3: 16-bit floating point -> torch.float16 or torch.half
#4: 8-bit integer(unsigned) -> torch.uint8
#5: 8-bit integer(signed) -> torch.int8
#6: 16-bit integer(signed) -> torch.int16 or troch.short
#7: 32-bit integer(signed) -> torch.int32 or torch.int
#8: 64-bit integer(signed) -> torch.int64 or torch.long





In [27]:
#Torch.device是表现torch.tensor被分配的设备类型的类，其中分为”cpu“和”cuda“两种
#如果设备序号没有显示则表示此tensor被分配到当前设备，
#比如:"cuda"等同于"cuda":X, X为torch.cuda.current_device()返回值
#我们可以通过tensor.device来获取其属性，同时可以利用字符或者字符+序号的方式来分配设备

#通过字符串
torch.device("cuda:0")
torch.device("cpu")
torch.device("cuda")#当前设备


#通过字符串和设备序号
torch.device("cuda",0)
torch.device("cpu",0)


#此外，cpu和cuda设备的转换可以通过使用”to“来实现
device_cpu = torch.device("cpu") #声明cpu设备
device_cuda = torch.device("cuda") #声明cuda设备
data = torch.Tensor([1])
data.to(device_cpu)#将数据转换为cpu格式
#data.to(device_cuda)#将数据转换为cuda格式，这里我们执行会报错，是因为没装cuda



tensor([1.])

In [42]:
#创建Tensor

#直接创建:torch.tensor(data, dtype=None, device=None, requires_grad=False)
#data--可以是list,tuple,numpy array, scalar等类型数据
#dtype--可以返回想要的tensor类型
#device--可以指定返回的设备
#requires_grad--可以指定是否进行记录图的操作，默认为false

#需要注意的是，torch.tensor()总是复制data,如果你想要避免复制，可以使用torch.Tensor.detach()
#如果是从numpy中获得的数据，那么可以使用torch.from_numpy()，注from_numpy()是共享内存的
torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
torch.tensor([0,1])
torch.tensor([[0.11,0.22,0.33]], dtype=torch.float64, device=torch.device('cpu',0))
#torch.tensor([0.11,0.22,0.33], dtype=torch.float64, device=torch.device('cpu',0))
torch.tensor(3.1411) #create a scalar(zero-dimensional tensor)
torch.tensor([])





tensor([1, 2, 3])
[1 2 3]
[-1  2  3]


In [43]:
#从numpy中获得数据：torch.from_numpy(ndarry)
#注：生成返回的tensor会和ndarry共享数据，任何对tensor的操作都会影响到ndarry。

import numpy
a = numpy.array([1,2,3])
t = torch.from_numpy(a)
print(t)
print(a)
t[0] = -1
print(a)

tensor([1, 2, 3])
[1 2 3]
[-1  2  3]


In [82]:
#创建特定的tensor

#根据数值要求

#torch.zeros(*size, out=None)返回大小为size的零矩阵
torch.zeros([2,2])
torch.zeros((2,2))
#上面的两种方式都生成了一个2*2的矩阵
a = torch.zeros(8) #生成一个长度为8的一维零矩阵

#torch.zeros_like(input)，返回与input相同size的零矩阵
torch.zeros_like(a)

#torch.ones(*sizes, out=None)返回大小为sizes的单位矩阵
#torch.ones_like(input),返回与input相同size的单位矩阵
torch.ones((3,4)) #等同于torch.ones([3,4])，后面的方法也是一样的

#torch.full(size, fill_value),返回大小为size,单位值为fill_value的矩阵
#torch.full_like(input, fill_value)，返回与input相同size，单位值为fill_value的矩阵
torch.full([2,3],4)

#torch.arange(star=0, end, step=1,...)，返回从start到end，单位步长为step的1d tensor
#也就是生成一个等差数列，起始值为start,末尾值为end-step，间隔为step
torch.arange(1,4,0.5)
torch.arange(1,6)#输出结果为tensor([1, 2, 3, 4, 5])，step默认为1，但不包括最后一个元素
torch.arange(start=1, end=4, step=0.5)

#torch.linspace(start, end, steps=100),返回从start到end，间隔中的插值数目为steps的1d tensor
#也是生成一个等差数列，起始值为start,末尾值为end，中间要有steps个元素值
torch.linspace(1,5,100)

#torch.logspace(start, end, steps=100,)返回从10^start到10^end的有steps个间隔的1d tensor
#这个具体怎么生成的没看懂，但是每一个元素都是前一个元素的平方值
torch.logspace(1,5,10)


tensor([1.0000, 1.0404, 1.0808, 1.1212, 1.1616, 1.2020, 1.2424, 1.2828, 1.3232,
        1.3636, 1.4040, 1.4444, 1.4848, 1.5253, 1.5657, 1.6061, 1.6465, 1.6869,
        1.7273, 1.7677, 1.8081, 1.8485, 1.8889, 1.9293, 1.9697, 2.0101, 2.0505,
        2.0909, 2.1313, 2.1717, 2.2121, 2.2525, 2.2929, 2.3333, 2.3737, 2.4141,
        2.4545, 2.4949, 2.5354, 2.5758, 2.6162, 2.6566, 2.6970, 2.7374, 2.7778,
        2.8182, 2.8586, 2.8990, 2.9394, 2.9798, 3.0202, 3.0606, 3.1010, 3.1414,
        3.1818, 3.2222, 3.2626, 3.3030, 3.3434, 3.3838, 3.4242, 3.4646, 3.5051,
        3.5455, 3.5859, 3.6263, 3.6667, 3.7071, 3.7475, 3.7879, 3.8283, 3.8687,
        3.9091, 3.9495, 3.9899, 4.0303, 4.0707, 4.1111, 4.1515, 4.1919, 4.2323,
        4.2727, 4.3131, 4.3535, 4.3939, 4.4343, 4.4747, 4.5152, 4.5556, 4.5960,
        4.6364, 4.6768, 4.7172, 4.7576, 4.7980, 4.8384, 4.8788, 4.9192, 4.9596,
        5.0000])

In [98]:
#创建特定的tensor

#根据矩阵的要求

#torch.eye(n, m=None, out=None...)，返回2D的单位对角矩阵
#默认的生成的是一个n*n的矩阵，如果强制给m赋值也可以
torch.eye(8)
torch.eye(n=8,m=4)
torch.eye(8,4)

#torch.empty(*size, out=None,...)返回被未初始化的数值填充，大小为sizes的tensor
#torch.empty_like(input,...)返回与input相同size，并被未初始化的数值填充的tensor
torch.empty(8)
torch.empty((2,4))


<class 'torch.Tensor'>


In [116]:
#创建特定的tensor
import torch
#随机采样生成

#torch.normal(mean, std, out=None)
#返回的是一个张量，包含从给定参数Means，std的离散正态分布中抽取随机数。
#均值means是一个张量，包含每个输出元素相关的正态分布的均值
#标准差值std是一个张量，包含每个输出元素相关的正态分布的标准差
#均值和标准差的形状不需要匹配，但每个张量的元素个数必须相同。
#参数：means(Tensor) -- 均值，也可以是一个值，表示后面的std几个张量共用一个mean值
#     std(Tensor) -- 标准差, 也可以是一个值，表示前面的mean几个张量共用一个std值
#     out(Tensor) --可选的输出张量
torch.normal(mean=torch.rand(5), std=torch.linspace(1,2,5))
torch.normal(mean=1, std=torch.linspace(1,2,5))
torch.normal(mean=torch.rand(5), std=2)


#torch.rand(*size, out=None, dtype=None)返回size个[0,1]之间均匀分布的随机数值
#troch.rand_like(input, dtype=None,...)返回与input相同size的tensor，填充均匀分布的随机数值
a = torch.rand(5)
torch.rand_like(a)


#torch.randint(low=0, high,size...)返回均匀分布的[low,high]之间的整数随机值,注意size需要是一个元组
#torch.randint_like返回与input相同size的tensor，填充均匀分布的随机数值
a = torch.randint(low=1, high=5,size=(3,))
torch.randint(1,5,(4,))
torch.randint_like(a, 2,4)


#torch.randn(*size, out=None,...)，返回大小为size，均值为0，方差为1的正太分布的随机数值
#torch.randn_like(input,dtype=None,...)
a = torch.randn(5)
torch.randn_like(a)


#torch.randperm(n, out=None, dtype=torch.int64)，返回0到n-1的数列的随机排列
torch.randperm(5)






tensor([1, 4, 0, 2, 3])

In [5]:
#Tensor的基本操作

#torch.cat(seq,dim=0, out=None),沿着dim连接seq中的tensor，所有的tensor必须有相同的size或者empty
#其相反的操作为torch.split()和torch.chunk()
#torch.stack(seq)的操作是直接再新增加一个维度，cat的操作其实是在原有的维度里面修改数值，
#stackl和cat的具体区别可以看下面的g和i的size区别

a = torch.Tensor([1,2,3])
b = torch.cat((a,a))
print(b)
b = torch.randn(8).reshape((2,4))
c = torch.rand(8).reshape((2,4))
d = torch.cat((b,c),dim=1)
print(c)
print(b)
print(d)

e = torch.arange(1,9).reshape(2,2,2)
f = torch.arange(9,17).reshape(2,2,2)
g = torch.cat((e,f))
h = torch.cat((e,f),dim=1)
i = torch.stack((e,f))
print(e)
print(f)
print(g)
print(g.size())
print(h)
print(h.size())
print(i)
print(i.size())

tensor([1., 2., 3., 1., 2., 3.])
tensor([[0.1671, 0.8666, 0.8820, 0.2945],
        [0.5202, 0.6667, 0.3512, 0.5016]])
tensor([[-1.0040, -0.6113, -0.9164,  0.4221],
        [-0.7211, -1.2085,  0.2746,  0.4474]])
tensor([[-1.0040, -0.6113, -0.9164,  0.4221,  0.1671,  0.8666,  0.8820,  0.2945],
        [-0.7211, -1.2085,  0.2746,  0.4474,  0.5202,  0.6667,  0.3512,  0.5016]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])
torch.Size([4, 2, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8],
         [13, 14],
         [15, 16]]])
torch.Size([2, 4, 2])
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
      

In [143]:
#torch.gather(input, dim, index, out=None)返回沿着dim搜集的新的tensor
#对于3D的张量来说，可以视为：
#if dim=0: out[i][j][k] = input[index[i][j][k]][j][k]
#if dim=1: out[i][j][k] = input[i][index[i][j][k]][k]
#if dim=2: out[i][j][k] = input[i][j][index[i][j][k]]

t = torch.Tensor([[1,2],[3,4]])
ind = torch.LongTensor([[0,0],[1,0]])
torch.gather(t,dim=0,index=ind)

#torch.split(tensor, split_size, dim),将tensor沿着dim维切分成split_size大小的tensor
#torch.chunk(tensor,chunks,dim)，将tensor沿着dim为切分成chunks组，如果不能整除的话，最后一块可以小一些
a = torch.Tensor([1,2,3])
torch.split(a,1)#输出结果为(tensor([1.]), tensor([2.]), tensor([3.]))，每组一个tensor
torch.chunk(a,1)#输出结果为(tensor([1., 2., 3.]),)切分成了1组
torch.chunk(a,2)#输出结果为(tensor([1., 2.]), tensor([3.]))，切分成了2组

(tensor([1., 2.]), tensor([3.]))

In [151]:
#torch.index_select(input, dim, index, out=None),
#在指定维度dim方向上从input中抽取由位置序列Index指定的值，
#output的其他维度的长度和原来的矩阵相同，在第dim维度上的长度和index的长度相同。


x = torch.randn(3,4)
print("x:",x)
indices = torch.LongTensor([0,2])
print(torch.index_select(x,0,indices))#dim=0
print(torch.index_select(x,1,indices))#dim=1





#torch.mask_select(input, mask, out=None),
#mask是一个ByteTensor，维度与input相同，true返回，false不返回，返回值不共用内存
#返回的结果为一个1D的Tensor
x = torch.randn(3,4)
print("x",x)
mask = x.ge(0.5)
print("mask",mask)
print(torch.masked_select(x,mask))



x: tensor([[-0.1488, -0.3783, -1.2725,  0.2263],
        [-0.0348,  0.2564,  1.5160,  0.6048],
        [-0.2523, -0.1958,  0.3398, -0.5247]])
tensor([[-0.1488, -0.3783, -1.2725,  0.2263],
        [-0.2523, -0.1958,  0.3398, -0.5247]])
tensor([[-0.1488, -1.2725],
        [-0.0348,  1.5160],
        [-0.2523,  0.3398]])
x tensor([[-1.9372, -0.0672,  0.7725,  1.2513],
        [-1.9247, -0.2642,  0.4124, -0.6706],
        [-0.0664, -0.3396,  0.7775, -0.9599]])
mask tensor([[0, 0, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 1, 0]], dtype=torch.uint8)
tensor([0.7725, 1.2513, 0.7775])


In [17]:
import torch
#矩阵的一些操作
#torch.transpose(input, dim0, dim1, out=None) 返回dim0和dim1交换后的tensor
#torch.t(input, out=None)，专为2D矩阵的转置，是transpose的便捷函数

a = torch.tensor([[1,2,],[3,4]]) 
print(a)
b = torch.transpose(a,0,1)
print(b)
c = torch.t(a)
print(c)


#torch.squeeze(input, dim, out=None)，移除默认所有size为1的维度，
#当dim指定时，移除size为1的维度。返回的tensor会和input共享存储空间，所以任何一个的改变都会影响另一个
#torch.unsequeeze(input, dim, out=None)，扩展input的size，如A*B变成1*A*B
a = torch.tensor([[1,2,3,4]])
d = torch.squeeze(a)
print(d)
e = torch.unsqueeze(d,dim=0)
print(e)


#torch.reshape(input, shape)，返回的size为shape具有相同数值的tensor，注意shape=(-1,)这种表述，-1表示任意的
a = torch.tensor([1,2,3,4,5,6])
b = a.reshape(2,-1)
print(b)





tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [19]:
#其他的一些操作

#torch.where(condition,x,y)，根据condition的值来相应x,y的值，true返回x的值，false返回y的值
#torch.unbind(tensor, dim=0)，返回tuple解除指定的dim的绑定，相当于按指定的dim拆分
a = torch.Tensor([[1,2,3],[4,5,6]])
b = torch.unbind(a,dim=0)#将一个(2,3),分成两个（3）
print(b)


#toch.nonzero(input,out=None),返回非零值的索引，每一行都是一个非零值的索引值
c = torch.nonzero(a)
print(c)








(tensor([1., 2., 3.]), tensor([4., 5., 6.]))
tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])


In [67]:
#Tensor的操作
#torch.tensor()根据后面给的data创建Tensor, Tensor类型根据数据进行推断
#torch.Tensor()是默认的tensor类型(torch.FloatTensor)的简称



a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.abs(a, out=None)#torch.abs()求绝对值
print(b)
#加法
c = torch.tensor([[7,8,9],[10,11,12]])
d = torch.tensor([[13,14,15],[16,17,18]])
e = torch.add(a,c)#torch.add()实现两个tensor相加
print(e)

#torch.addcmul(tensor, value,tensor1,tensor2,out=None)
#用tensor2对tensor1逐元素相乘，并对结果乘以标量值value然后加到tensor上，
#张量形状不需要匹配，但是元素数量必须一致
f = torch.addcmul(a,1,c,d)
print(f)

#torch.addcdiv(tensor, value=1, tensor1, tensor2,out=None)
#用tensor2对tensor1逐元素相除，然后乘以标量值value并加到tensor上
g = torch.addcdiv(a,1,d,c)
print(g)



#除法
#torch.div(input, value, out=None)，将Input逐元素除以标量值value，并返回结果到输出张量out
a = torch.tensor([[1,2,3],[4,5,6]])
c = torch.div(a,4)
print(c)

#乘法
#torch.mul(input, other,out=None)，两个张量按元素相乘，并返回到输出张量，
#两个张量的形状不须匹配，但是总元素数须一致。当形状不匹配时，input的形状作为输出张量的形状。
b = torch.mul(a,a)
print(b)



#幂运算
#torch.pow(input,exponent, out=None), y_i = input^(exponent)
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.pow(a,2)
print(b)


#指数运算
#torch.exp(tensor, out=None)，y_i = e^(x_i)
#torch.expm1(tensor, out=None), y_i = e^(x_i) - 1
#a = torch.FloatTensor([[1,2,3],[4,5,6]])
a = torch.Tensor([[1,2,3],[4,5,6]]) #创建的a默认的floatTensor类型
#a = torch.tensor([[1,2,3],[4,5,6]])
#这个a是torch.tensor创建的，那么根据后面给的1,2,3等数据，将其判定为LongTensor，所以执行torch.exp()会报错
b = torch.exp(a)
print(b)


#对数运算
#torch.log(input, out=None), y_i = log_e(x_i)
a = torch.Tensor([[1,2,3],[4,5,6]])#这里的a是floatTensor
#a = torch.tensor([[1,2,3],[4,5,6]])会报错，因为这时a是longTensor
b = torch.log(a)
print(b)


#截断函数
#torch.ceil(input, out=None)，对输入input的每个元素向上取整
#torch.floor(input, out=None)，对输入inout的每个元素向下取整
#torch.round(input,out=None),返回相邻最近的整数，四舍五入
#torch.trunc(input, out=None)，返回整数部分
#torch.frac(input, out=None),返回小数部分
#torch.fmod(input, divisor, out=None)，返回input/divisor的余数
#torch.remainder(input, divisior, out=None)，返回input/divisior的除数
a = torch.randn(3,4)
print(a)
b = torch.ceil(a)
b = torch.floor(a)
b = torch.round(a)
b = torch.trunc(a)
b = torch.frac(a)
b = torch.fmod(a,2)
b = torch.remainder(a,2)
print(b)



tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 92, 114, 138],
        [164, 192, 222]])
tensor([[2, 3, 4],
        [5, 6, 7]])
tensor([[0, 0, 0],
        [1, 1, 1]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5982, 148.4132, 403.4288]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
tensor([[-1.0280,  1.5283, -0.5479,  0.8545],
        [-0.0129,  0.5519,  0.8314, -1.8394],
        [-1.4780, -0.1044, -0.2210, -0.3757]])
tensor([[0.9720, 1.5283, 1.4521, 0.8545],
        [1.9871, 0.5519, 0.8314, 0.1606],
        [0.5220, 1.8956, 1.7790, 1.6243]])


In [87]:
#tensor的降维操作
a = torch.Tensor([[1,2,3],[4,7,6]])

#torch.argmax(input, dim=None, keepdim=False),返回最大值的索引值
b = torch.argmax(a)
print("The max element index is:", b)

#torch.argmin(input, dim=None, keepdim=False)，返回最小值的索引值
b = torch.argmin(a)
print("The min element index is:",b)

#torch.cumprod(input, dim, out=None),
#返回当前维度前面的所有元素连乘的结果，y_i = x_1*x_2*x_3...*x_i
#这里dim的替换，一样思考a[i][j]，当dim=0，则变成a[i+1][j]，当dim=1，则变成a[i][j+1]
b = torch.cumprod(a,1)
c = torch.cumprod(a,0)
print("The dim=1 multipule result is:",b)
print("The dim=0 multipule result is:",c)

#torch.cumsum(input, dim, out=None),
#返回当前维度前面的所有元素相加的结果，y_i = x_1 + x_2 +...+x_j
#这里的dim思考方式同上
b = torch.cumsum(a,dim=0)
c = torch.cumsum(a, dim=1)
print("The dim=0 add result is:", b)
print("The dim=1 add result is:", c)

#torch.dist(input, out, p=2)
#返回input和output的p式距离,差值的平方和再开方
a = torch.Tensor([[1,2,3],[4,5,6]])
b = torch.Tensor([[1,3,5],[6,7,8]])
c = torch.dist(a,b)
print("The p distance between a and b is:",c)



#torch.mean()，返回平均值
#torch.sum()，返回总和值
#torch.median()，返回中间值
#torch.mode()，返回众数值
#torch.std()，返回标准差
#torch.var()，返回方差
#torch.unique(input, sorted=False)，去重操作，相当于取set，返回一个1-D的唯一的tensor
#torch.prod(input, dim, keepdim=False)，返回指定维度的乘积结果，一个值

a = torch.Tensor([1,2,3,4,4,5,5,5,])
b = torch.mean(a)
c = torch.sum(a)
d = torch.median(a)
e = torch.mode(a)
f = torch.std(a)
g = torch.var(a)
h = torch.unique(a)
i = torch.prod(a)
print("The element average is:",b)
print("The element sum is:",c)
print("The element median is:",d)
print("The element mode is:",e)
print("The tensor std is:",f)
print("The tensor var is:",g)
print("The unique tensor is:",h)
print("The multipule result is:",i)



The max element index is: tensor(4)
The min element index is: tensor(0)
The dim=1 multipule result is: tensor([[  1.,   2.,   6.],
        [  4.,  28., 168.]])
The dim=0 multipule result is: tensor([[ 1.,  2.,  3.],
        [ 4., 14., 18.]])
The dim=0 add result is: tensor([[1., 2., 3.],
        [5., 9., 9.]])
The dim=1 add result is: tensor([[ 1.,  3.,  6.],
        [ 4., 11., 17.]])
The p distance between a and b is: tensor(4.1231)
The element average is: tensor(3.6250)
The element sum is: tensor(29.)
The element median is: tensor(4.)
The element mode is: (tensor(5.), tensor(7))
The tensor std is: tensor(1.5059)
The tensor var is: tensor(2.2679)
The unique tensor is: tensor([4., 3., 5., 2., 1.])
The multipule result is: tensor(12000.)


In [89]:
#tensor的对比操作

#torch.equal(tensor1, tensor2)，如果tensor1与tensor2有相同的size和elements，则为true，否则为false
a = torch.equal(torch.tensor([1,2,3]), torch.tensor([1,2,3]))
b = torch.equal(torch.tensor([1,2,3]), torch.tensor([1,2,2]))
print("The result of torch.equal:",a)
print("The result of torch.equal:",b)





The result of torch.equal: True
The result of torch.equal: False


In [93]:
#torch.eq(tensor1, tensor2,out=None),按照每个元素进行对比，如果相等则为1，如果不等则为0
a = torch.eq(torch.tensor([[1,2],[3,4]]), torch.tensor([[1,3],[3,5]]))
print("The result of torch.eq is:",a)

#torch.ge(input, other,out=None),input >= other则为1，否则为0
a = torch.ge(torch.tensor([[1,2],[3,4]]), torch.tensor([[1,3],[3,5]]))
print("The result of torch.ge is:",a)

#torch.gt(input, other, out=None),input>other则为1，否则为0
a = torch.gt(torch.tensor([[1,2],[3,4]]), torch.tensor([[1,3],[3,5]]))
print("The result of torch.gt is:", a)

#同理torch.le(input, other, out=None)，input<=other则为true，否则为false
#torch.lt(input, other, out=None)，input<other则为true，否则为false

#torch.ne(input, other, out=None)，只有当input != other时才为1，相等时为0
a = torch.ne(torch.tensor([[1,2],[3,4]]), torch.tensor([[1,3],[3,5]]))
print("The result of torch.ne is:", a)

The result of torch.eq is: tensor([[1, 0],
        [1, 0]], dtype=torch.uint8)
The result of torch.ge is: tensor([[1, 0],
        [1, 0]], dtype=torch.uint8)
The result of torch.gt is: tensor([[0, 0],
        [0, 0]], dtype=torch.uint8)
The result of torch.ne is: tensor([[0, 1],
        [0, 1]], dtype=torch.uint8)


In [114]:
#tensor的其他一些操作

#torch.cross(input, other, dim=-1, out=None)，实现叉乘，外积
#这里是返回沿着维度dim上，两个张量Input的叉积，Input和other必须具有相同的形状，且指定的dim维度上size必须为3，
#如果不指定dim，则默认为第一个尺度为3的维度
#这个的具体计算暂时还未弄清楚，向量的外积和内积的区别
a = torch.cross(torch.tensor([[1,2,3],[3,4,5]]), torch.tensor([[1,3,3],[3,4,5]]))
print("The result of torch.cross is:", a)

#torch.dot(tensor1, tensor2)，
#返回tensor1和tensor2的点乘,其中tensor1和tensor2都必须为1D向量，对位相乘在相加
a = torch.dot(torch.tensor([1,2,3,4]), torch.tensor([1,3,3,5]))
print("The result of torch.dot is:", a)


#torch.mm(mat1, mat2, out=None),返回矩阵mat1和mat2的乘积,注意他执行的是矩阵的乘法
a = torch.mm(torch.tensor([[1,2],[3,4]]), torch.tensor([[1,3],[3,5]]))
print("The result of torch.mm is:", a)


#torch.eig(a, eigenvectors=False, out=None)，返回矩阵a的特征值和特征向量
a = torch.eig(torch.Tensor([[1,2],[3,4]]))
print("The result of torch.eig is:", a)


#torch.det(A)，返回矩阵A的行列式
a = torch.det(torch.Tensor([[1,2],[3,4]]))
print("The result of torch.det is:",a)

#torch.trace(input)，返回2D矩阵的迹
a = torch.trace(torch.Tensor([[1,2],[3,4]]))
print("The result of torch.trace is:",a)

#torch.diag(input, diagonal=0, out=None),输出也是tensor
#如果输入是一个向量，则返回一个以input为对角线元素的2D方阵,其他元素为0
#如果输入是一个矩阵，则返回一个包含input为对角元素的1D张量
#如果diagonal=0，返回的是主对角线上的元素
#如果diagonal>0，则返回的是主对角线之上的元素
#如果diagonal<0，则返回的是主对角线之下的元素

a = torch.diag(torch.Tensor([[1,2],[3,4]]), diagonal=0)
b = torch.diag(torch.Tensor([1,2,3,4]), diagonal=0)
print("The result of torch.diag is:", a)
print("The result of torch.diag is:",b)


#torch.histc(input, bins=100, min=0, max=0, out=None)
#计算input的直方图，如果min和max都为0，则利用数据中的最大最小值作为边界
#这个没弄明白具体的计算细节
a = torch.histc(torch.Tensor([1,2,3,4]))
print("The result of torch.histc is:",a)



#torch.tril(input, diagonal=0, out=None),返回矩阵的下三角矩阵，其他为0
#torch.triu(input, diagonal=0, out=None），返回矩阵的上三角矩阵，其他为0

a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tril(a)
c = torch.triu(a)
print("The result of torch.tril is:",b)
print("The result of torch.triu is:",c)



The result of torch.cross is: tensor([[-3,  0,  1],
        [ 0,  0,  0]])
The result of torch.dot is: tensor(36)
The result of torch.mm is: tensor([[ 7, 13],
        [15, 29]])
The result of torch.eig is: (tensor([[-0.3723,  0.0000],
        [ 5.3723,  0.0000]]), tensor([]))
The result of torch.det is: tensor(-2.0000)
The result of torch.trace is: tensor(5.)
The result of torch.diag is: tensor([1., 4.])
The result of torch.diag is: tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 4.]])
The result of torch.histc is: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 